### ISSUE TITLE
component not registered !

### ISSUE THREAD

**Issue by Jordanadopo** [EmilStenstrom/django-components#11]
Hi! In my template index.html, i tried to call my component named "login" and it's wrong with that error.
I want to get a tutorial containing configuration in a whole django folders. Thanks for your answer in advance!

**Comment by EmilStenstrom** [comment]
@Jordanadopo Could you post your configuration according to the README?

**Comment by dongfengweixiao** [comment]
I have same question! @EmilStenstrom can you provide ONE FULL RUNNABLE DJANGO PROJECT for research.THX.

**Comment by EmilStenstrom** [comment]
@dongfengweixiao If you post a simple example site as a new repo, and try to make it work, I can have a look and see if I can get it to work! Would that be OK?

**Comment by dongfengweixiao** [comment]
> @dongfengweixiao If you post a simple example site as a new repo, and try to make it work, I can have a look and see if I can get it to work! Would that be OK?

Forgive me for my poor English, examples in the following link：https://github.com/dongfengweixiao/django_components_example, thx for your help.

**Comment by dongfengweixiao** [comment]
> @dongfengweixiao If you post a simple example site as a new repo, and try to make it work, I can have a look and see if I can get it to work! Would that be OK?

THX U,now i found erron and fix it.

**Comment by EmilStenstrom** [comment]
@dongfengweixiao @Jordanadopo The latest version of django_components now auto-detects components when they are specified in a components.py file inside your installed apps. Please try again and let me know how it works.
