### ISSUE TITLE
[Question] can the asset files (css, js) for the components work with webpack to bundle everything?

### ISSUE THREAD

**Issue by simkimsia** [EmilStenstrom/django-components#114]
I am thinking of using this with something like https://github.com/AccordBox/python-webpack-boilerplate

**Comment by EmilStenstrom** [comment]
I haven’t tried using this together with webpack. How come you need webpack at all? Typescript?

**Comment by simkimsia** [comment]
Yes I'm thinking of moving to typescript permanently
