### ISSUE TITLE
Ability to choose which components JS/CSS to load

### ISSUE THREAD

**Issue by David-Guillot** [EmilStenstrom/django-components#143]
Hi there,

We have a page that initially doesn't render any component, but is able to insert into its DOM some HTML fragments (through htmx or hotwired or stuff like that), which themselves may carry some components.

With current `django-components` capabilities, we have two options when calling `{% component_js_dependencies %}` :
* If the `ComponentDependencyMiddleware` is disabled, JS from all components will be loaded, which is suboptimal
* If the middleware is enabled, no component JS will be loaded, as the page template doesn't hold any `{% component mycomponent %}` ; that forces us to load JS with the classic `<script src="{% static 'path/to/component.js' %}">`

My first thought would be to add optional arguments to `component_js_dependencies`/`component_css_dependencies`, listing components that have a chance to appear on this page. Do you think it's the way to go? If so, I can work on a PR :wink:

**Comment by EmilStenstrom** [comment]
Hi @David-Guillot!

Your use-case makes a lot of sense for sites with dynamic content. I'm open to adding options for component_(js/css)_dependencies like you suggest. Do you have a suggestion of what the syntax should be?

I think using the keyword "preload" to signify that you are forcing some dependencies to be rendered, but others might be loaded as per the normal rules.

Maybe: `{% component_js_dependencies preload="calendar,button,form" %}`?

I think allowing optional spacing after the comma is probably a good idea.

**Comment by David-Guillot** [comment]
Thank you for your quick answer :smile:  .

I hadn't thought of a parameter name ; my first instinct would be `force` instead of `preload` because I prefer naming things after what they do rather than what we want to use them for. But that's up to you :wink: . I'll work on a PR tomorrow!

**Comment by EmilStenstrom** [comment]
I think I prefer preload because it's closing to what it's doing relative to what the ComponentDependencyMiddleware is doing. The middleware loads components when they are used, but the use case here is "render components even though they are not used yet, because they will be used soon". To me, that's just preload, the same way preloading a stylesheet with a `<link rel="preload">` tag does.

Looking forward to a PR!

**Comment by David-Guillot** [comment]
Okay, thanks for your input :+1:
