### ISSUE TITLE
Allow single quoting of component names

### ISSUE THREAD

**Issue by rbeard0330** [EmilStenstrom/django-components#15]
If you write a component tag like: `{% component_block 'my_list' %}`, you currently get a `NotRegistered` Error for the component 'my_list' (not my_list unquoted).  I believe the correct (and intended) behavior is that the template tag should strip both single quotes and double quotes before doing the lookup.

The line in `do_component` is 
```
component_name = component_name.strip('"')
```
which I think should be:
```
component_name = component_name.strip('"\'')
```

**Comment by EmilStenstrom** [comment]
Thanks for reporting this little annoyance, I just released 0.4.2 which fixes this problem.
