### ISSUE TITLE
Use component name as variable

### ISSUE THREAD

**Issue by housUnus** [EmilStenstrom/django-components#152]
I'm trying to use a conditional component based on the parent parameters, I'm calling the component not by its name but with a variable containing its name, which is very helpful in many cases.

The problem is that your "component" tag is treating the component name parameter as a string, so when I use a variable name  like this:
`{% component_block variable_name %}`
 I get an error saying:
`django.template.exceptions.TemplateSyntaxError: Component name 'variable_name' should be in quotes`

I tried to make it work by adding some `filter ""|add:variable_name` but it didn't work, this trick worked for me with the include tag of Django.

Thanks

**Comment by EmilStenstrom** [comment]
@housUnus This sounds like something this library should support, good suggestion! Can you write up a PR to add that support?

**Comment by housUnus** [comment]
Hi, I've added a pull request containing the necessary modifications in order to support the feature, I'm ready to discuss these modifications.
