### ISSUE TITLE
Handling missing context_variables in slotted templates and passing kwargs in {% component_block %}

### ISSUE THREAD

**Issue by rbeard0330** [EmilStenstrom/django-components#16]
Sorry for putting both of these in one issue, but they're both so minor it seemed excessive to open separate issues:

1.  In slotted components, trying to include a variable that isn't available in the context raises an exception.  The reason seems to be that the render path for slotted components uses `nodelist.render()`, which automatically binds the template, rather than `template.render()`, which does not.  The problem goes away if the template is manually bound.

2.  Using {% component_block variable="XYZ" %}, it is currently an error if the component's `context` function inserts additional variables into the context (e.g., default parameters).  The issue is that if there are any arguments specified in the tag, `ComponentNode.render()` runs the entire context through the dictcomp that resolves `FilterExpression`s to generate `extra_context`.  This can be fixed by passing anything that doesn't have a `resolve` method through the dictcomp unchanged.

I put together a PR to demonstrate the issues and fix them--will send shortly.

**Comment by EmilStenstrom** [comment]
Great finds! I'll add some comments to the PR, but looks really good! Thanks for helping me make django-components better!

**Comment by EmilStenstrom** [comment]
Just released 0.4.3 with your fixes!
