### ISSUE TITLE
Passing variable from view function to component_block part

### ISSUE THREAD

**Issue by alem88** [EmilStenstrom/django-components#173]
Take a look at this for example
{% component_block "calendar" date="2020-06-06" %}
I would like to put a variable instead of "2020-06-06" through my view function. Is that possible and if it is, how? I tried something like date={{var_name}}, but it failed.

**Comment by alem88** [comment]
I just figured out...  date=var_name
Thank you for this library

**Comment by EmilStenstrom** [comment]
Happy you solved it!
