### ISSUE TITLE
Tailwind CSS + daisyUI + django-components

### ISSUE THREAD

**Issue by jej** [EmilStenstrom/django-components#180]
I would love to see these 3 working together!

I haven't looked too much here but I guess it's possible without much effort.

Thanks for this app.

https://tailwindcss.com
https://daisyui.com

**Comment by David-Guillot** [comment]
I guess that would be named... Djaisy 😎 

More seriously, I think it's a great idea, but to be implemented as a distinct library, in order to keep django-components lightweight.

**Comment by jej** [comment]
Not missing it! That's why I said "I guess it's possible without much effort" :)

**Comment by EmilStenstrom** [comment]
Oh, so this issue is that you would like to see an example of how they work together?

**Comment by jej** [comment]
The issue was just a wish and an idea! I think there is a logic between these 3 tools. I don't know if I will use django-components. Maybe django templates are handy enough to produce tailwind/daisyui contents. But if you provide an example it's nice of course. Maybe other people could be interested too.

**Comment by TawalMc** [comment]
Awesome. Today I was thinking about using django-tailwind and daisy UI and tonight I read about the usage with django-component. I'm on the good path. I search about django-components after watching @David-Guillot  presentation on django-conf.

Good job. (Sorry I know we must talk about issues here, but I would just add this comment).

**Comment by EmilStenstrom** [comment]
I'm closing this issue since there are nothing stopping you from using tailwind or daisyui with django-components.

**Comment by jej** [comment]
of course, no problem.
thanks.
