### ISSUE TITLE
django-components not working when deployed to apache2 server

### ISSUE THREAD

**Issue by Youssefihab33** [EmilStenstrom/django-components#182]
I used django-components in development, working just fine, using the django development server.

Currently I am deploying the web application to my apache2 server, the rest of the app is working fine but when i open a page that should have a component, it raises the following error:
`
NotRegistered
The component "bgShowCard" is not registered
/home/Youssef/env/lib/python3.10/site-packages/django_components/component_registry.py, line 28, in get
shows.views.home_view
/home/Youssef/env//bin/python
3.10.6
['/home/Youssef/Desktop/SIMSY',  '/usr/lib/python310.zip',  '/usr/lib/python3.10',  '/usr/lib/python3.10/lib-dynload',  '/home/Youssef/env/lib/python3.10/site-packages']
Sat, 15 Oct 2022 13:18:14 +0200
`
It's kinda odd that no one asked about this before but can the plugin be used in a production server like apache2?

**Comment by EmilStenstrom** [comment]
Hi. This isn't likely a problem with django-components, but with you having different settings in local and production. Very hard to guess which setting...
