### ISSUE TITLE
Packing css & js components files into one file 

### ISSUE THREAD

**Issue by housUnus** [EmilStenstrom/django-components#184]
Many components imply many CSS & JS files which affect the loading speed of the page, it would be better if all CSS & JS files get packed into one single file (CSS FILE & JS FILE) which will make improve the loading speed;

**Comment by EmilStenstrom** [comment]
This is something that you can use an asset manager to fix. There's an open issue to document how to use an asset manager together with Django here: https://github.com/EmilStenstrom/django-components/issues/39
