### ISSUE TITLE
Add keyword "optional" to slot to make it optional to fill

### ISSUE THREAD

**Issue by housUnus** [EmilStenstrom/django-components#189]
The "Block" component of django doesn't throw error when the block is not called from the inheriting template, many times some slots might not be needed when component called, but if not mentioned will throw error, and that implies declaring it empty.

**Comment by EmilStenstrom** [comment]
I kind of like to get errors when things do not behave as expected. What do you think about adding a way to make a slot optional, byt declaring it `{% slot optional %}...{% endslot %}`? The optional keyword would surpress the error.

**Comment by housUnus** [comment]
i think it would do the job.

**Comment by EmilStenstrom** [comment]
Are you open to writing up a PR and tests for it?

**Comment by housUnus** [comment]
Hi, sorry for the long time response, I've found out that anything added outside the slot while filling the component will throw an error of "Content tokens in component blocks must be inside of slot tags: ", so I think we should allow adding blocks outside slots by removing the last part that throws the error.
Regards

**Comment by EmilStenstrom** [comment]
@housUnus Can you show a code example of how you expect to use django-components together with blocks?

**Comment by housUnus** [comment]
Django principle when dealing with NESTED blocks is the same as THE LIBRARY, if you tried to use nested BLOCKS it won't work, I don't see it as an issue, once I'm using the BLOCK on the inheriting child, it means I'm redefining its structure including everything declared inside of it from the parent.

**Comment by EmilStenstrom** [comment]
Sorry, I got confused and started talking about a separate issue here. Deleted the two comment to avoid going off track.

**Comment by lemontheme** [comment]
The latest version (v0.26) makes filling slots optional by default.

Slots that should raise an exception if no fill is provided should be marked with the new `required` keyword. Example:

```Django
{% load component_tags %}
<div class="header-box">
  <h1>{% slot "title" required %}{% endslot %}</h1>
  <h2>{% slot "subtitle" %}{% endslot %}</h2>
</div>
```

Does this resolve your issue, @housUnus? I believe it should, but I could use an example of what you're describing in your last comment. Otherwise, let me know if we can close this :)
