### ISSUE TITLE
Remove requirement for CSS in the Media class

### ISSUE THREAD

**Issue by timothyis** [EmilStenstrom/django-components#225]
Hi there, firstly; thanks for working on this project. It has made moving to Django from a pure React past a lot easier. 

Just to preface; I am not a Python dev, but a frontend dev working in a Django environment, so excuse my lack of knowledge surrounding it.

We are using Tailwind CSS in our project and have no need for a CSS file for each component, but I would like to have just a JS file in order to write some custom scripts for each component. However, when I try and add a `Media` class to a component with just `js`, an error occurs, so I assume this isn't supported. 

It would be amazing to remove the requirement of having both CSS and JS files when defining `Media` (I assume others might even want just a CSS file and not a JS file), in order to support workflows like ours and so I don't have to load a render blocking unused CSS file.

**Comment by EmilStenstrom** [comment]
Hi @timothyis! Thanks for the suggestion, which makes a lot of sense. It was an easy fix, so I went ahead and fixed it right away, and this is now supported in version 0.25 of the library. Hope it works well for you!

**Comment by timothyis** [comment]
Thank you very much, Emil! That was amazingly fast and greatly appreciated!

**Comment by EmilStenstrom** [comment]
Happy to help! I'd love to see wider adoption of django-components. For that, we need to handle all the common use-cases people have. Tailwind with no CSS makes a lot of sense!

**Comment by timothyis** [comment]
If it helps understand our use-case; we use django-components commonly with Alpine.js and use Tailwind CSS globally, so there's normally little need for either JS or CSS files, however, writing Alpine.js within the HTML is getting very messy, so I'm moving it to the JS file. 

This workflow really closely matches what I was looking for when starting to work with Django templates and moving away from front-end JS frameworks.
