### ISSUE TITLE
Zero documentation on location of component modules

### ISSUE THREAD

**Issue by danjac** [EmilStenstrom/django-components#23]
In the README:

"We create a Component by inheriting from the Component class and specifying the context method. We also register the global component registry so that we easily can render it anywhere in our templates."

However there is no documentation on how the components are discovered: for example templatetags in Django are automatically loaded for all registered app, or explicitly added in the TEMPLATES config. There doesn't appear to be a similar process for component files: adding a component.py file under an app doesn't work, nor does there appear to be a way to add "global" components in settings.  Django admin uses a similar pattern.

So for example I have this component.py file under an app:
```

class Button(component.Component):
      ... # 

component.registry.register(name="button", component=Button)
```

This module is not autodiscovered (using for example autodiscover_modules) so it is not registered. Calling this:

`{% component name="button" %}`

Raises a NotRegistered error.

**Comment by danjac** [comment]
EDIT: the only way I could get this to work was by including the components in an existing template tags module. Not sure if that's the "right" way but again, no documentation available.

**Comment by EmilStenstrom** [comment]
@danjac That's a great point. I've always just added an import to my __init__.py for that app, and thinking about it, I think it's a great point to add a default app location like components.py that automatically gets discovered. I did not know about autodiscover_modules.

PR appreciated that adds support for this! :)

**Comment by danjac** [comment]
Sure: was thinking about automatically looking for a components module under each app (just like admin.py) and maybe a setting for "global" components - things like buttons etc that aren't app-specific: perhaps something like:

```
COMPONENTS = {
   "autodiscover": True,
   "libraries": ["path/to/my/global_components"]
}
```

**Comment by danjac** [comment]
https://github.com/EmilStenstrom/django-components/pull/24/files

**Comment by EmilStenstrom** [comment]
Thanks for fixing this in the best of ways, via a PR! :)
