### ISSUE TITLE
Only load dependencies when component is in use

### ISSUE THREAD

**Issue by EmilStenstrom** [EmilStenstrom/django-components#29]
Adding an issue here to track this, as this is something I think is something we really need. Ping @rbeard0330.

**Comment by rbeard0330** [comment]
I'll get this up for you to look at sometime today!

**Comment by EmilStenstrom** [comment]
Awesome! Feel free to put up more issues if there are things you think we should build sometime :)

**Comment by EmilStenstrom** [comment]
Closed by #52 (which was a copy of #35)
