### ISSUE TITLE
Components directory can't be found when multiple settings files are used

### ISSUE THREAD

**Issue by bastinc** [EmilStenstrom/django-components#290]
I'm using different settings files (base.py, dev.py, prod.py) which are stored in a settings directory. The composent directory is at the root of the project.

In this case, django-components fails to register components in the components directory.

```
 raise NotRegistered('The component "%s" is not registered' % name)
django_components.component_registry.NotRegistered: The component "calendar" is not registered
```

**Comment by EmilStenstrom** [comment]
This is now available in 0.35 of django-components. Thanks @dylanjcastillo!
