### ISSUE TITLE
Access to "request" and other global context variables

### ISSUE THREAD

**Issue by danjac** [EmilStenstrom/django-components#30]
Does django-components have a way to access context or do you have to pass in "request" manually?

Django template tag decorators have a "takes_context" argument that does this, so I was wondering if this is something that could be supported.

**Comment by EmilStenstrom** [comment]
Yes! This is something that @rbeard0330 fixed recently! By default all context is inherited and can be used inside components and slots. There's even a short section about how it works in the docs: https://github.com/EmilStenstrom/django-components#component-context

Do tell if there's something that doesn't work as you expect!

**Comment by danjac** [comment]
Excellent! Thanks.
