### ISSUE TITLE
Problem with Selective Loading of JavaScript Files using `{% component_js_dependencies %}` Tag

### ISSUE THREAD

**Issue by Macktireh** [EmilStenstrom/django-components#305]
Hello,

I've encountered an issue while using the `{% component_js_dependencies %}` tag within the Django Components project. When I use this tag in a page that only uses a specific component, for example, the `Head` component, the tag doesn't load just the JavaScript files related to the `Head` component. Instead, it seems to load all JavaScript files from all components.

### Steps to Reproduce:

1. Create a `Home` page that uses the `Head` component exclusively.
2. Use the `{% component_js_dependencies %}` tag on this page to load JavaScript dependencies.

```html
<!-- home.html -->

{% extends 'base.html' %}
{% load static %}

{% block title %} Home {% endblock title %}

{% block style %} {% endblock style %}

{% block header %}
    {% component 'head' %}
{% endblock header %}

{% block content %} {% endblock content %}

{% block footer %} {% endblock footer %}

{% block js %}
    {% component_js_dependencies %}
{% endblock js %}

```

### Expected Behavior:

I expected the `{% component_js_dependencies %}` tag to load only the JavaScript files related to the `Head` component used on the current page (in this case, the `Head` component).

### Observed Behavior:

However, the `{% component_js_dependencies %}` tag seems to load all JavaScript files from all components, even if those components are not used on the current page.

![Capture d'écran 2023-08-10 223808](https://github.com/EmilStenstrom/django-components/assets/49348001/44129268-58f4-4a43-a513-52128c3664eb)

![Capture d'écran 2023-08-10 223020](https://github.com/EmilStenstrom/django-components/assets/49348001/090b9b54-749f-48d2-9669-199dcd30d48d)

Environment:

- python (version 3.10.11)
- poetry (version 1.4.2)
- django (version 4.2.1)
- django-components (version 0.28.1)
- Browser: Chrome (Version 115)
- Operating System: Windows 11

Thank you.

Best regards,

**Comment by EmilStenstrom** [comment]
Hello @Macktireh. We are loading all dependencies by default just to make sure to prime the browser cache for the next page load. Everything will then load instantly.

If you just want the components that are currently in use, the simple way to do this is to add our middleware. It's currently not documented (and we're tracking it here: https://github.com/EmilStenstrom/django-components/issues/71), but I think you could get it working with some fiddling. Is the info there enough for you to solve your issue?

**Comment by Macktireh** [comment]
Hello @EmilStenstrom. Thank you very much for your response and for clarifying how the {% component_js_dependencies %} tag works. I now understand why it loads all dependencies by default.

I will explore the option of adding the middleware you mentioned, and I will closely follow the discussion related to this feature (#71). It could be an interesting solution to load only the dependencies of currently used components.

Once again, thank you for your assistance and for the work you are doing on the Django Components project!

Best regards,
