### ISSUE TITLE
ImportError: cannot import name 'Generic' from 'typing' 

### ISSUE THREAD

**Issue by acivitillo** [EmilStenstrom/django-components#308]
I get this error with versions of Python 3.9, 3.10, and 3.11. It comes from the import in the `typing.py` module. I am not sure if it is connected, but I am running django-components on Windows.

**Comment by EmilStenstrom** [comment]
Hello! Could you give the full stacktrace so we can see where that import error comes from?

**Comment by EmilStenstrom** [comment]
@acivitillo It looks from your stacktrace as if the errors originates in django_unicorn? Could it be that they don't support some python version?

**Comment by EmilStenstrom** [comment]
Feel free to open if I'm mistaken.
