### ISSUE TITLE
slot.super?

### ISSUE THREAD

**Issue by danjac** [EmilStenstrom/django-components#33]
Suppose I have a component with a slot:

```
<div>
  {% slot  header %}some default content...{% endslot %}
</div>

```
There doesn't appear to be a way to do something like {{ block.super }} i.e.

```
{% component_block "my-component" %}
{% slot header %}
some new content 
{{ slot.super }}
{% endslot %}
```

**Comment by EmilStenstrom** [comment]
Great suggestion, I'm 👍 for adding this.

**Comment by rbeard0330** [comment]
An inelegant, but easy, way to support this would be to make a variant of the slot tag that doesn't have a body and just adds the default content. On its own, this wouldn't do anything, but you can use the same slot name multiple times, so you could build up a final slot that looks the way you want through a combination of "real" slot tags and the new default slot tag.

**Comment by EmilStenstrom** [comment]
@rbeard0330 I would like to stick as close to how `{% block %}` works as possible as this is what I think people expect, and therefore might make django-components easiest to learn. So I think supporting this use case would mean to add a dict to the context of each slot with the name `slot` and the content `{"super": "Default content for this slot"}`. That would mean `{{ slot.super }}` returns the correct thing.
