### ISSUE TITLE
ImportError due to Circular Import in auto-discover Process with django-unicorn

### ISSUE THREAD

**Issue by allieus** [EmilStenstrom/django-components#334]
I've encountered an issue while using the django-unicorn library where a circular import occurs during the auto-discover process. Specifically, the code import typing within django-unicorn/components/typing.py appears to reference itself, which leads to an ImportError.

<img width="1195" alt="image" src="https://github.com/EmilStenstrom/django-components/assets/13359/dbeb982c-3143-4df0-add6-be802942052b">

Would it be feasible to introduce a configuration option in the settings of django-unicorn to allow specific apps to be excluded from the auto-discover process? Implementing this feature could offer a more flexible way to manage imports and help avoid circular reference issues like the one I've encountered.

**Comment by EmilStenstrom** [comment]
This repo is not about django-unicorn?

**Comment by allieus** [comment]
I understand that this is a separate project. However, when using django-components in conjunction with django-unicorn, the components folder in django-unicorn seems to trigger the error mentioned above during the autodiscover process of django-components.

I wonder if it might be beneficial for django-components' autodiscover function to have the capability to exclude components folders that do not comply with the rules of django-components. This is why I am raising this issue.

Thank you. :-)

**Comment by EmilStenstrom** [comment]
I wonder if actually fixing the error would be easier in this case? The error message you post is because django-unicorn is written for a later version of Python than the one you use. That should be something that's easy to fix right?
