### ISSUE TITLE
Automatic components from a template file

### ISSUE THREAD

**Issue by EmilStenstrom** [EmilStenstrom/django-components#337]
I was thinking it's a good idea to allow people to just write a template, and infer the python code needed from that. Similar to how this works, but with minimal python code: https://mitchel.me/slippers/docs/getting-started/

Any ideas of what the interface could be?

**Comment by firdaus-aziz** [comment]
Currently I am using this https://github.com/carltongibson/django-template-partials

**Comment by EmilStenstrom** [comment]
@firdaus-aziz How does it compare to this project?

**Comment by firdaus-aziz** [comment]
Sorry for the late reply.

For web components I use - https://github.com/Xzya/django-web-components

**Comment by EmilStenstrom** [comment]
@firdaus-aziz django-web-components seems very similar to this project. I too like the component "name" more because it doesn't pollute the namespace as much. 

Why do you like django-template-partials? Because you can render one partial at the time with a web request?

**Comment by firdaus-aziz** [comment]
> Why do you like django-template-partials? Because you can render one partial at the time with a web request?

Yes, precisely. 

1. It makes my views easier
2. I can see all the "partials" in one file. Previously it was a spaghetti of files with many blocks and includes.

```
# views.py
if request.htmx.target == "card":
    template = "list_page.html#card"
elif request.htmx.target == "table":
    template = "list_page.html#table"
elif request.htmx.target == "main":
    template = "list_page.html#main"
else:
    template = "list_page.html"
```

Sorry if I'm unable to better describe/explain my preferences for django-template-partials. English not my first language.

**Comment by EmilStenstrom** [comment]
Don't worry about not having English as first language, it's not mine either :)

The point of django-components is to replace both the two libraries you mention by allowing you to model both web components and template partials as components. I think what's missing to do this is to be able to render just a component for a HTMX request, but this is not something this specific issue is about. If you see something that would make switching from both those libraries to this one, feel free to open a new issue.

**Comment by EmilStenstrom** [comment]
Nah, I'm withdrawing this request. What this would do is just save a few lines of code, that's not enough of a win to take on increased complexity.
