### ISSUE TITLE
Nested slots don't work 

### ISSUE THREAD

**Issue by danjac** [EmilStenstrom/django-components#34]
Example:

```
  {% slot form_footer %}
  <div class="flex items-center justify-end">
    {% slot form_buttons %}{% endslot %}
  </div>
  {% endslot %}
```

I use the component thus:

```
{% component_block "form" %}
{% slot form_buttons %}
<button>Submit</button>
{% endslot %}
{% endcomponent_block %}

```
The content of the form_buttons is not overridden, i.e. it's empty. Only the outer content of form_footer is rendered:

```
  <div class="flex items-center justify-end">
  </div>

```

**Comment by EmilStenstrom** [comment]
Ah, makes sense that nested slots, just like nested blocks, should work. 

Internally the slots are handled as a list, so supporting this would mean handling them as a tree instead. Not trivial, but doable I think.

Mind giving it a try?

**Comment by danjac** [comment]
I'm not very familiar with the underlying template tag code, but naively could you run the same code as `do_component_block() `inside the slot tag: so each slot just renders its own list of slots?
