### ISSUE TITLE
Pylance(reportIncompatibleVariableOverride): "Media" overrides symbol of same name in class "Component"

### ISSUE THREAD

**Issue by jbrulmans** [EmilStenstrom/django-components#367]
Hello, `pylance` is throwing an error on `class Media:` when I am trying to register a new component. 
It component itself works, I was just wondering if there is something I can do without wanting to immediately ignore the `pylance` error: 

    from django_components import component

    @component.register("navigation_bar")
    class NavigationBar(component.Component):
        template_name = "navigation_bar/navigation_bar.html"

        class Media:
            css = "navigation_bar/navigation_bar.css"
            js = ""

The full error is:

`
"Media" overrides symbol of same name in class "Component"
  "app.components.navigation_bar.navigation_bar.NavigationBar.Media" is incompatible with "django_components.component.Component.Media"
  Type "type[app.components.navigation_bar.navigation_bar.NavigationBar.Media]" cannot be assigned to type "type[django_components.component.Component.Media]"Pylance[reportIncompatibleVariableOverride](https://github.com/microsoft/pyright/blob/main/docs/configuration.md#reportIncompatibleVariableOverride)
component.py(71, 11): Overridden symbol
`

Thanks in advance!

**Comment by EmilStenstrom** [comment]
Hi @jbrulmans,

I've afraid the typing of this project could use some work. We currently don't even have CI set up to verify types. This should probably be the first step to get this working.

Would you be willing to contribute a fix for this?

**Comment by jbrulmans** [comment]
Hi @EmilStenstrom, thanks for getting back to me so quick.
No worries, I thought there might have been an easy config fix or change.
Atm I don't have a huge amount of time to look into this, but I might be at a certain point in the future.
I don't have a huge experience with doing something like this, but sounds like an interesting thing to try.
For now, feel free to close the issue or keep it open. How you'd like.

**Comment by EmilStenstrom** [comment]
@jbrulmans This should be fixed in 0.52. Please reopen if that's not true.
