### ISSUE TITLE
django_components.component_registry.AlreadyRegistered error when using component as view.

### ISSUE THREAD

**Issue by Fingel** [EmilStenstrom/django-components#368]
Hello!
I found this library because I had the exact same use case in mind as outlined in this issue: https://github.com/EmilStenstrom/django-components/issues/349
I would like to use Django + HTMX, and being able to return a single component as a view fits perfectly. I believe this has the potential to become a very powerful paradigm.

It's mentioned in https://github.com/EmilStenstrom/django-components/issues/349#issuecomment-1891103065 that the author of the PR needed to explicitly register each component to avoid the `AlreadyRegistered` error. The pull request here by @dylanjcastillo  https://github.com/EmilStenstrom/django-components/pull/366 mentions that a modification had to be made to not raise an error if the same component is registered twice. 

I still get the error, so I'm wondering if this is not working as intended, or perhaps a different step needs to be taken? I haven't taken a look at the PR yet, but I'll be happy to debug.

**Comment by Fingel** [comment]
OK, I think I've found the root cause. The class hash function here:
https://github.com/EmilStenstrom/django-components/blob/91b4accfebf74f3f7a8cf2ecab03789a1979d578/django_components/component.py#L93
will return 2 different hashes if a class is imported using a different path. 

Take for example, a Todo component with a .py file under `components/todo/todo.py`. When using the regular `@component.register("todo")` wrapper, the return value of `cls.__module__` is `todo`.

However, if you import the module in another file, such as `urls.py` like this:
```python
from components.todo.todo import TodoComponent

urlpatterns = [...]
```
the return value of `cls.__module__` will be `components.todo.todo`.

This is an issue because the documentation at
https://github.com/EmilStenstrom/django-components/blob/91b4accfebf74f3f7a8cf2ecab03789a1979d578/README.md?plain=1#L449 instructs you to place your components `urls.py` in the top level `components` folder, and import the example competent like so:

`from calendar import Calendar`

However this import _will not work_ if the urls.py module is in a directory above the calendar folder. You need to write it like this:

`from components.calendar.calendar import Calendar` 

or use a relative import. Either way, the hash function will not match because the module will not simply be `calendar`.

The only way to get this to work is if where you are importing the module (such as in a `urls.py`) is in the same module as where the component is defined. And indeed, in the sample/test project that the component views tests use:
https://github.com/EmilStenstrom/django-components/blob/91b4accfebf74f3f7a8cf2ecab03789a1979d578/sampleproject/components/urls.py

the `urls.py` file is in the same folder as `greeting.py` where the component is actually defined. So in this case, the hash function will match - but this does not match what the documentation says to do.

So I think there are two options:
1. Update the documentation to say that the `urls.py` file needs to be in the same directory as the module that defines the component, or
2. Make the has function a bit more robust so that it stands up to imports from different paths.

**Comment by EmilStenstrom** [comment]
Hi @Fingel! Before going further into troubleshooting this: Are you sure you're using the latest version of the code? I JUST released 0.34 to pypi. Which version are you using? Does things work when you run the latest release?

**Comment by EmilStenstrom** [comment]
@dylanjcastillo Is on it. 

It was me who suggested this (faulty) change in the PR review, going with Dylan's original suggestions would have avoided this! :)

**Comment by dylanjcastillo** [comment]
@Fingel, I got the PR for this now. Please give it a try, and let us know if it works!

@EmilStenstrom, no worries. I should've included a specific test for this, and we have that now!

**Comment by Fingel** [comment]
Yes! It works now. Nice work. The python import system is so funky.
