### ISSUE TITLE
Question about inheritance of properties in `get_context_data`

### ISSUE THREAD

**Issue by jbrulmans** [EmilStenstrom/django-components#379]
Hello, I have a question that might someone else have already solved or an idea how to solve it. 
Basically, I would like to create a base component for specific button components I am building. I currently have a `AbstractButton` that holds a specific set of properties that all of these share, like so:

```python
    @component.register("abstract-button")
    class AbstractButton(component.Component):
    template_name = "abstract/abstract_button/abstract_button.html"

    def get_context_data(
        self,
        size: Size | None = None,
        variant: ButtonVariant | None = None,
        accessibility_text: str | None = None,
        elevation: bool | None = False,
        disabled: bool | None = False,
    ):
        return {
            "size": size,
            "variant": variant,
            "accessibility_text": accessibility_text,
            "elevation": elevation,
            "disabled": disabled,
        }

    class Media:
        css = "abstract/abstract_button/abstract_button.css"
```

With the template looking like this then: 

```django
    <button class="focus-target focus-style" {% if accessibility_text %}aria-label={{ accessibility_text }} title={{ accessibility_text }}{% endif %} size={{ size }} variant={{ variant }} {{ elevation|yesno:"elevation," }} {{ disabled|yesno:"disabled," }}>
        <div class="touchable-zone"
             aria-hidden="true"></div>
        {% slot "content" %}{% endslot %}
    </button>
```

The idea with this abstract button class would be that I can easily re-use the template of the base class and slot in specific other code to create for example an `IconButton` or a normal `Button`.  I would however somehow would like to extend the variables (properties) in the `get_context_data`, instead of having to pass them all forward everytime. So creating some kind of inheritance between the components. At the moment my `IconButton` looks like:

```python
    @component.register("icon-button")
    class IconButton(component.Component):
      template_name = "icon-button/icon-button.html"
  
      class Media:
          css = "icon-button/icon-button.css"
  
      def get_context_data(
          self,
          icon_name: str,
          icon_color: str | None = None,
          size: IconButtonSize = IconButtonSize.L,
          variant: ButtonVariant = ButtonVariant.PRIMARY,
          accessibility_text: str | None = None,
          elevation: bool | None = False,
          disabled: bool | None = False,
          notification: str | None = None,
      ):
          return {
              "icon_name": icon_name,
              "icon_color": icon_color,
              "icon_size": ICON_SIZES_BY_BUTTON_SIZE[size],
              "size": size,
              "variant": variant,
              "notification": notification,
              "accessibility_text": accessibility_text,
              "disabled": disabled,
              "elevation": elevation,
              "is_dot": self.__is_dot(size),
              "notification_variant": self.__notification_variant(disabled),
          }
```

The template using the `abstract-button` class as a base with slotting in some extra things:

```django
    {% component_block "abstract-button" size=size variant=variant accessibility_text=accessibility_text elevation=elevation disabled=disabled %}
        {% fill "content" %}
            {% component "svg-icon" icon_name=icon_name icon_size=icon_size color=icon_color %}
            {% if notification %}
                {% component_block "badge" outlined=True dot=is_dot variant=notification_variant %}
                    {% fill "notification" %}
                        {{ notification }}
                    {% endfill %}
                {% endcomponent_block "badge" %}
            {% endif %}
        {% endfill %}
    {% endcomponent_block "abstract-button" %}
```

As you can see, from a template point of view, this seems to work fine and can be a decent solution for extending. However the `get_context_data` can get bloated quite fast if you have to keep passing forward all the attributes of the base class. I am currently developing components which have even more properties and I feel like there should be a better solution on how to do this. 

I tried creating frozen `@dataclass`-es, and just passing this class as a dict forward, put as I just figured out, Django does not allow to define `dicts` in there templating language (first time working with Django) and I don't want to pass a different dict for every different component in the context through the view. It wouldn't make sense to instantiate the properties of the component anywhere else but the template. 

Did anyone ever do something similar or have an idea? It would be greatly appreciated 🙏
Please reach out if you have any questions.

**Comment by dylanjcastillo** [comment]
@jbrulmans Would something like this work?

```python
from django_components import component

from components.abstract_button import AbstractButton


@component.register("icon-button")
class IconButton(AbstractButton):
    template = """
        {% component_block "abstract-button" size=size variant=variant accessibility_text=accessibility_text elevation=elevation disabled=disabled %}
            {% fill "content" %}
                ...
            {% endfill %}
        {% endcomponent_block %}
    """

    def get_context_data(
        self,
        icon_name: str,
        icon_color: str,
        **kwargs,
    ):
        params = super().get_context_data(**kwargs)
        params["icon"] = icon
        return params
```

**Comment by jbrulmans** [comment]
@dylanjcastillo I am currently getting the following error:

`django_components.component_registry.AlreadyRegistered: The component "abstract-button" is already registered`

I guess because of the import the imported component, `AbstractButton` in this case, is being re-registered for the second time 🤔 @EmilStenstrom any ideas?

**Comment by dylanjcastillo** [comment]
@jbrulmans what version of django-components are you using?

Can you share the code of the components or a similar example and how your directories are structured?

**Comment by jbrulmans** [comment]
@dylanjcastillo Damn, didn't notice there was another new version. That fixed it for me ! 
Thanks so much for thelp @dylanjcastillo ❤️
