### ISSUE TITLE
Adding HTML, JS, and CSS typing hints

### ISSUE THREAD

**Issue by dylanjcastillo** [EmilStenstrom/django-components#390]
To get syntax highlighting in VSCode for single-file components, I think we should include typing hints for HTML, CSS, and JS.

You can use [sourcetypes](https://pypi.org/project/sourcetypes/), but I think it'd be nice if we provided that directly, to avoid installing an additional library.

What do you think?

I'd be happy to open a PR for that.

**Comment by EmilStenstrom** [comment]
Agreed, we should include it as a dependency!

**Comment by EmilStenstrom** [comment]
This is now supported in django-components==0.51: https://pypi.org/project/django-components/0.51/
