### ISSUE TITLE
Add support for MyPy

### ISSUE THREAD

**Issue by JuroOravec** [EmilStenstrom/django-components#394]
I've started using MyPy recently, and for `django-components`, I get an error

```
Skipping analyzing "django_components": module is installed, but missing library stubs or py.typed marker
```

I haven't looked yet into how to make a library compatible with mypy, but I assume it shouldn't be too complicated. I can look into it if greenlit.

Let me know what you think @EmilStenstrom.

**Comment by EmilStenstrom** [comment]
@JuroOravec Supporting mypy, and getting better typing support, is interesting!

**Comment by JuroOravec** [comment]
Thanks! Please see https://github.com/EmilStenstrom/django-components/pull/396
