### ISSUE TITLE
Allow rendering JS / CSS parts of {% component_dependencies %} separately?

### ISSUE THREAD

**Issue by davidfstr** [EmilStenstrom/django-components#40]
First, thank you for creating this library. It looks very promising for providing some structure to components rendered on a page!

I am considering what it would take to migrate my own Django app at work to use django-components in the future, and I notice only one notable issue:

The `{% component_dependencies %}` tag which injects `<script>`-includes and `<link rel="stylesheet">`-includes appears to only be configurable to inject *both* JS and CSS at the same time in the same place.

However my existing pages include CSS and JS separately for performance reasons, with CSS at the top in the `<head>` (to immediately style HTML that appears later) and JS at the bottom after the `<body>` (to avoid blocking initial HTML rendering). Therefore I would like to be able to spell something like:

```
{% load component_tags %}
<!DOCTYPE html>
<html>
<head>
    <title>My example calendar</title>
    {% component_css_dependencies %} 👈 
</head>
<body>
    {% component "calendar" date="2015-06-19" %}
</body>
{% component_js_dependencies %} 👈 
<html>
```

Here I've **split `{% component_dependencies %}` into two forms, one which injects CSS and the other which injects JS:**

* CSS: `{% component_css_dependencies %}` (or maybe `{% component_css %}`, or maybe `{% component_dependencies type='css' %}`)
* JS: `{% component_js_dependencies %}` (or maybe `{% component_js %}`, or maybe `{% component_dependencies type='js' %}`)

What are your thoughts on allowing separate injection by type, in this fashion?

---

(As a separate item, `{% component_css_dependencies %}` and `{% component_js_dependencies %}` is quite a lot to type. Something shorter like `{% component_css %}` and `{% component_js %}` might be nicer.)

**Comment by EmilStenstrom** [comment]
Hi @davidfstr,

This actually is already possible, just badly documented. The split versions are better for several reasons, so I've simply [changed the readme to recommend those versions](https://github.com/EmilStenstrom/django-components/commit/b30506087c278fd6c3451513bfef04d813b407ce) instead. The names are `component_[css/js]_dependencies` which are a bit long, but I'll keep them to keep the library backwards compatible.

There are not a huge number of users of this library yet, so I'm looking forward to hearing your thoughts as you try it out. PR:s are always welcome, especially if they keep to the high standard if this issue description! :D
