### ISSUE TITLE
Python versions support policy (drop 3.6/3.7?)

### ISSUE THREAD

**Issue by GabDug** [EmilStenstrom/django-components#418]
Hey :wave:

To use pyproject.toml packaging in #417, I had to drop Python 3.6. Here's an issue to discuss that.

## Summary

I propose to change the support Policy from "all Python versions allowed by the Django versions we target against" to "all Python versions currently receiving active or security support that are allowed by the Django versions we target against":

| Python version | Django version           |
|----------------|--------------------------|
| ~~3.6~~           | ~~3.2~~                     |
| ~~3.7~~            | ~~3.2~~                      |
| 3.8            | 3.2, 4.0, 4.1, 4.2       |
| 3.9            | 3.2, 4.0, 4.1, 4.2       |
| 3.10           | 3.2, 4.0, 4.1, 4.2, 5.0  |
| 3.11           | 4.1, 4.2, 5.0            |
| 3.12           | 4.2, 5.0                 |

> Python 3.7 could still be a target, as tooling is still more up-to-date for it.

## Proposed Change

I see that django-components still supports Python 3.6 and 3.7, released in 2018 and 2020, [which no longer receive active or security support](https://endoflife.date/python).

While I agree that a broad support of Python version is nice to have to some users, I'm questioning whether it could make maintenance and evolution of the project harder.

While [Pypistats](https://pypistats.org/packages/django-components) data should be taken with a grain of salt, we see that the number of downloads for Python 3.6 is almost 0 (2 downloads in 120 days) and quite low for 3.7. Unfortunately, we can't know if those downloads are for a current of previous version of django-components.

Removing 3.6 and 3.7 would only impact users of Django 3.2: we could argue that users of Django 3.2 that still upgrade their packages regularly have already moved to Python 3.8, 3.9 or 3.10, as a lot of packages in the Python ecosystem only support active version of Python.

This change would allow to have more modern tools and with consistent versions in the CI, as many tools dropped support for those versions.

E.g: 3.6 has different, older versions for almost all tools used in CI: `distlib-0.3.8 filelock-3.4.1 importlib-metadata-4.8.3 importlib-resources-5.4.0 packaging-21.3 platformdirs-2.4.0 pluggy-1.0.0 py-1.11.0 pyparsing-3.1.2 six-1.16.0 toml-0.10.2 tox-3.28.0 tox-gh-actions-2.12.0 typing-extensions-4.1.1 virtualenv-20.17.1 zipp-3.6.0`, but also for `pip`, `setuptools`, `wheel`.

Using actively maintained tools could also help in the packaging, either by using recent `setuptools` features or by switching to another powerful packager like `hatchling`.

**Comment by EmilStenstrom** [comment]
Great to read your reasoning, it makes sense. I am pro this change.

I would simplify wording of the support policy to: "All officially supported combinations of [Python](https://devguide.python.org/versions/#versions) and [Django](https://docs.djangoproject.com/en/dev/faq/install/#what-python-version-can-i-use-with-django)".

**Comment by EmilStenstrom** [comment]
There's a small script that helps update the supported Python/Django versions automatically. If the policy changes this script would need to change too: https://github.com/EmilStenstrom/django-components/blob/master/scripts/supported_versions.py

**Comment by GabDug** [comment]
@EmilStenstrom Nice to hear your feedback! I have already hacked the script for #417, but I'll try to fetch the active Python versions properly.

**Comment by EmilStenstrom** [comment]
Well done! I just merged it! :)
