### ISSUE TITLE
Bug: `"context_behavior": "isolated"` does not have the same effect as `only` keyword

### ISSUE THREAD

**Issue by JuroOravec** [EmilStenstrom/django-components#421]
I upgraded from v0.31 to v0.63 and wanted to use the `context_behavior` setting:

```py
COMPONENTS = {
    "context_behavior": "isolated",
}
```

However, when testing it out, it turns out that setting  `context_behavior` to `isolated` does not nothing.

Looking into to code, I think this has to do with the comparison in https://github.com/EmilStenstrom/django-components/blob/master/src/django_components/templatetags/component_tags.py#L338, where we compare Enum against a string.

```py
if app_settings.CONTEXT_BEHAVIOR == "isolated":
    return bits, True
```

This will always return `False` unless the enum class inherits from `str` too ([See this thread](https://stackoverflow.com/a/63028809/9788634))

```py
class Signal(str, Enum):
    red = 'red'
    green = 'green'
    orange = 'orange'

brain_detected_colour = 'red'
brain_detected_colour == Signal.red  # direct comparison
```

So the fix should be a one-liner, modifying the [`ContextBehavior` enum](https://github.com/EmilStenstrom/django-components/blob/84db2b7314a5bccc83b3854e81316c42a157d59c/src/django_components/app_settings.py#L7) to inherit also from `str`.

But while we're at it we should also add tests that check this feature.

**Comment by EmilStenstrom** [comment]
That's a great find, and an obvious case of a missing test as you say.
