### ISSUE TITLE
Hot reload doesn't work with specific project setup (django 5 + single file components)

### ISSUE THREAD

**Issue by EmilStenstrom** [EmilStenstrom/django-components#423]
- I nailed it down to single file components not working. Once I split the components it works like a charm!
- The files have to be in the dir I defined in STATICFILES_DIR otherwise it does not work / component not registered error gets thrown

_Originally posted by @liquidiert in https://github.com/EmilStenstrom/django-components/issues/191#issuecomment-2039531429_

**Comment by dylanjcastillo** [comment]
@liquidiert could you provide a sample repo that reproduces this error? It works for me

https://github.com/EmilStenstrom/django-components/assets/7218756/c8d8b185-9299-4a89-ab16-619c2edf43c3

**Comment by liquidiert** [comment]
@dylanjcastillo Created a [repository](https://github.com/liquidiert/reproducible_sfc_not_working). I suspect it has smth to do with the cookiecutter template used. I understand if it's not on your roadmap to support custom stuff like this :) But still might be interesting

**Comment by dylanjcastillo** [comment]
Thank you @liquidiert. 

Yes, this looks like something to do with the way the project is structured. I'll try to look at it, but I have limited time these days, so might take a while.

**Comment by EmilStenstrom** [comment]
@liquidiert Would you mind trying your repo with the latest version of django-components, and enable logging? You'll see the full list of paths that are searched for which might give a hint of what the problem is.

**Comment by liquidiert** [comment]
@EmilStenstrom I've updated django-components to `0.66` and turned on logging. Unfortunately I can't see the full list of search paths you mentioned. Do I have to set up smth else for that?

**Comment by dylanjcastillo** [comment]
Hey @liquidiert,

I researched this a bit today. It seems to be a caching issue related to Django's `cached.Loader`. For some reason, in your project configuration, it doesn't restart the server when you change single file components. It occurs when you add `django-component`'s `template_loader.Loader` to the loaders but I couldn't figure out why (and I don't have enough knowledge about this topic).

There's a workaround you could use (though I didn't test it thoroughly). Only add `django_components.template_loader.Loader` when `DJANGO_DEBUG=FALSE`:

```python
# In commons.py
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            # Contains plain text templates, like `robots.txt`:
            BASE_DIR
            / "templates",
        ],
        "OPTIONS": {
            "context_processors": [
                # Default template context processors:
                "django.contrib.auth.context_processors.auth",
                "django.template.context_processors.debug",
                "django.template.context_processors.i18n",
                "django.template.context_processors.media",
                "django.contrib.messages.context_processors.messages",
                "django.template.context_processors.request",
            ],
            "loaders": [
                (
                    "django.template.loaders.cached.Loader",
                    [
                        "django.template.loaders.filesystem.Loader",
                        "django.template.loaders.app_directories.Loader",
                        # "django_components.template_loader.Loader", <- Remove this
                    ],
                )
            ],
            "builtins": [
                "django_components.templatetags.component_tags",
            ],
        },
    }
]

## Append to loaders if not DEBUG
if not DEBUG:
    TEMPLATES[0]["OPTIONS"]["loaders"][0][1].append("django_components.template_loader.Loader")
```

I hope that helps!

**Comment by liquidiert** [comment]
Hey @dylanjcastillo that is really weird. But thanks for the workaround!

**Comment by EmilStenstrom** [comment]
The cached loader shouldn't be used when developing. It makes sense that changes within templates that are cached are not reloaded. Great find Dylan, I'm closing this.
