### ISSUE TITLE
Logo for the project

### ISSUE THREAD

**Issue by EmilStenstrom** [EmilStenstrom/django-components#424]
I saw that @GabDug was thinking about a logotype for the project and started fiddling just for fun. 

The idea was the illustrate the concept that a component is a python class that brings together HTML, CSS, and JS. I liked the idea of making the logo a chemical bond with four parts. I first made it "vector 3D" but then started simplifying it to something that can be used as a symbol, even as a small favicon.

Without further ado:

![image](https://github.com/EmilStenstrom/django-components/assets/224130/1535ff00-503d-4b58-9185-e42034dcbf2f)

Thoughts?

**Comment by dylanjcastillo** [comment]
I'm all in for minimalistic icons. I like the second one better!

**Comment by JuroOravec** [comment]
Logo looking great! For the font, I'd remove the italization to make it easier to read.

**Comment by EmilStenstrom** [comment]
Thanks for the feedback!

![image](https://github.com/EmilStenstrom/django-components/assets/224130/47cb6965-334a-4ae8-a4b1-dc6455f57f46)

So let's go with the non-italic black/white version. I'll update the readme!
