### ISSUE TITLE
Fix misleading example component docs 

### ISSUE THREAD

**Issue by franciscobmacedo** [EmilStenstrom/django-components#426]
# The problem
The calendar example component in the [README.md](https://github.com/EmilStenstrom/django-components?tab=readme-ov-file#create-your-first-component) has some misleading configuration.

### Wrong js and css filenames and filepaths 
The example component ilustrates the creation of `calendar.js` and `calendar.css` files. However, in the [Media class](https://github.com/EmilStenstrom/django-components#:~:text=class%20Media%3A%0A%20%20%20%20%20%20%20%20css%20%3D%20%22style.css%22%0A%20%20%20%20%20%20%20%20js%20%3D%20%22script.js%22) it points to different files: `script.js` and `style.css` - both the names and their paths are wrong. There are some other comments in the code snippets that also point to those files.

### Wrong filepath in the `template_name` variable
The [template_name variable](https://github.com/EmilStenstrom/django-components#:~:text=template_name%20%3D%20%22calendar.html%22) points to `calendar.html` when it should be `calendar/calendar.html`.

# The solution
I suggest we follow what the command `startcomponent` does:

- change the css file name`style.css` and the `css` variable in the `Media` class should be `calendar/style.css`
- change the js file name to `script.js` and the `js` variable in the `Media` class should be `calendar/script.js` 
- change the `template_name`variable to `calendar/template.html`
- update the screenshot to match this changes

**Comment by EmilStenstrom** [comment]
Thanks you @franciscobmacedo, it seems you are right. The mkdocs branch is very early still, with lots of work to do, so I suggest we make a separate PR right away. Mind writing one up?
