### ISSUE TITLE
Clarification on "hot reload" - templates or python files?

### ISSUE THREAD

**Issue by anichols-bto** [EmilStenstrom/django-components#429]
Hi and thanks for the cool project!

I've noticed in my project, changes to `.py` files in the recommended `components/**` dir(s) do **not** trigger `StatReload` to restart the dev server (`runserver`) while changes to templates are reflected on page reload (without requiring the server to restart). 

Is this known/expected behavior?

Is the latter what is referred to as "hot-reload" in the other issues like #191 ?

**Comment by EmilStenstrom** [comment]
Yes, this is the same as https://github.com/EmilStenstrom/django-components/issues/423 - If you can drop a comment with your setup that doesn't work there it would be much appreciated.
