### ISSUE TITLE
Doc bug: component_tags instead of django_components

### ISSUE THREAD

**Issue by tanssinet** [EmilStenstrom/django-components#447]
The README says "To avoid loading the app in each template using {% load django_components %}, you can add the tag as a 'builtin' in settings.py"

This should probably be:

{% load component_tags %}

**Comment by dylanjcastillo** [comment]
Hey @tanssinet, you’re right about his and the other doc issue you reported. Thanks for letting us know.

Would you like to open a PR to fix those issues?

**Comment by tanssinet** [comment]
Sure. I did not make PR before because I was unsure whether there is some other source for the docs besides README.
