### ISSUE TITLE
Async middleware

### ISSUE THREAD

**Issue by TheSteveBurgess** [EmilStenstrom/django-components#464]
Hi,

Are there any plans to implement async in the current middleware? At the moment using the django-components middleware forces the entire request pipeline to be sync as the middleware doesn't support a async.

Cheers,

Steve.

**Comment by JuroOravec** [comment]
Hey @SteveBurgessStantec, I don't see why not. From [the docs](https://docs.djangoproject.com/en/5.0/topics/http/middleware/#asynchronous-support), it looks like making an async copy of the [ComponentDependencyMiddleware middleware](https://github.com/EmilStenstrom/django-components/blob/master/src/django_components/middleware.py#L28) should do the trick.

Do you have a project that uses async middlewares? Could you hack together a PR and check if things work for you? Or alternatively some demo project that we could use for testing. I think demo project in the repo is synchronous, and so is the project where I use django-components, so I don't have a quick way to test if things work.

**Comment by SteveBurgessStantec** [comment]
Hey @JuroOravec  I converted it earlier in dev and its looks like its working fine :)

Let me just check internally and see if i'm allowed to share the code. If i get the OK I'll create a PR.

**Comment by TheSteveBurgess** [comment]
I've created the PR now (i think!). You'll have to excuse me, it's been a very long time since I've created pull requests on Github :)

Let me know if you need anything from me.

**Comment by JuroOravec** [comment]
Merged in https://github.com/EmilStenstrom/django-components/pull/466
