### ISSUE TITLE
Topic on new behaviour for dispatching slots using 'include' tags

### ISSUE THREAD

**Issue by alexandreMartinEcl** [EmilStenstrom/django-components#484]
## Context

In our team, we used to work with version 0.16, and recently have decided to upgrade to a more modern one.

However, we had this component that now does not work anymore :

```
{# base.html#}

{% if some_type %}
    {% include 'component/_partials/_type_a.html' %}
{% else %}
  {% include 'component/_partials/_type_b.html' %}
{% endif %}
```

With each a and b template being a usual component template, defining a _slot_ "body" at a different place.

## Change

With version 0.52, it throws this error
> Instance of SlotNode was not linked to Template before use in render() context

Seems like behaviour of `_process_template_and_update_filled_slot_context` 

I upgraded untill 0.70, and can see now that in the method [in_node](https://github.com/EmilStenstrom/django-components/blob/2316f79dff66260b7a9fe91effb55c74524deca0/src/django_components/slots.py#L344), it will just not consider a `include node` :
```
        node = entry.node
        if not isinstance(node, SlotNode):
            return
```

## Question

So is it intended that `include` cannot be used anymore in _component_ templates ? Or am I missing something ?

**Comment by JuroOravec** [comment]
Hey @alexandreMartinEcl, thanks for noting this down. Could you include also the code for the component class?

And could you try to upgrade to [version 0.71](https://github.com/EmilStenstrom/django-components/releases)? Compatibility with the `include` tag was addressed in this MR https://github.com/EmilStenstrom/django-components/pull/468.

**Comment by alexandreMartinEcl** [comment]
Thank you for such a quick answer. This release came on point ! It seems to have solved it, thank you for the fix!
