### ISSUE TITLE
Better support for AlpineJS

### ISSUE THREAD

**Issue by EmilStenstrom** [EmilStenstrom/django-components#488]
### Discussed in https://github.com/EmilStenstrom/django-components/discussions/471

<div type='discussions-op-text'>
<sup>Originally posted by **JuroOravec** May  2, 2024</sup>
## Description

In my project, we use Django + AlpineJS, I've made a few changes that allow me to pass AlpineJS bindings through components more intuitively. Basically it's the same concept as [Vue's passthrough/fallthrough attributes](https://vuejs.org/guide/components/attrs#fallthrough-attributes).

So I can pass AlpineJS syntax like `@click.stop` to my Django components.
</div>

We would like to support namespaces parameters to the component template tag. 

```django
    {% component attrs:@click.stop="..." attrs:x-data="..."  %}
```
The colon in the parameter name would mean that we will gather all parameters with that name into a dict, and send that dict to get_context_data. 

```python
    def get_context_data(attrs): return {"attrs": attrs}
```

I would suggest we make this dict a new kind of dict, a "htmldict", so it can automatically be rendered in HTML without any changes:

```html
<div {{ attrs }}>
```
```html
<div @click.stop="..." c-data="...">
```

**Comment by zachbellay** [comment]
Very supportive of this proposal as it would also support htmx in addition to Alpine.js. For example, with a button component

```py
{% component "button" 
    attrs:hx-post={% url 'document-upload' document_uid=document.uid %}"
    attrs:hx-target="#document-output" %}
    Upload Document
{% endcomponent %}
```

**Comment by EmilStenstrom** [comment]
@zachbellay I don’t think nesting tags like that would work, but you can get the url “as url” on a separate line and then use it like you do there. I’m excited about it too!

**Comment by JuroOravec** [comment]
Hi all, this feature has just been released as v0.74 🎉 See the [README section "Rendering HTML attributes"](https://github.com/EmilStenstrom/django-components/tree/0.74?tab=readme-ov-file#rendering-html-attributes)

**Comment by zachbellay** [comment]
Wow! Great work @JuroOravec && @EmilStenstrom !! You guys worked at an amazing speed to get this out, great work!

**Comment by EmilStenstrom** [comment]
I take none of the credit here, all the hard work is done by @JuroOravec 🥳
