### ISSUE TITLE
Refactor accessing of default slot from `as var` to kwarg

### ISSUE THREAD

**Issue by JuroOravec** [EmilStenstrom/django-components#502]
See https://github.com/EmilStenstrom/django-components/pull/495#discussion_r1607117487

**Comment by JuroOravec** [comment]
Btw, @EmilStenstrom, what do you think of dropping the `.default` property when accessing the default slot?

Currently, we assign the slot to a variable with `{% fill "xxx" as "alias_name" %}`, and then we have to access the default slot via the "default" property as `alias_name.default`.

Since we already have `slot_data` directly on the `fill` tag, which we access as `{% fill "xxx" slot_data="abc" %}`, then IMO we should also access the default slot directly.

So instead of:

```django
{% fill "xxx" default="orig_slot" %}
	{{ orig_slot.default }}
{% endfill %}
```

We'd drop the `.default`, and have only:

```django
{% fill "xxx" default="orig_slot" %}
	{{ orig_slot }}
{% endfill %}
```

Above, I used the kwarg `default="..."` as a replacement for the `as "..."` syntax.

**Comment by EmilStenstrom** [comment]
Using default="orig_slot" looks much better! I think this is a good API.

**Comment by JuroOravec** [comment]
Wrote an MR for this at https://github.com/EmilStenstrom/django-components/pull/504, @EmilStenstrom would you give it a look?
