### ISSUE TITLE
Inline tests/templates to make tests easier to follow

### ISSUE THREAD

**Issue by EmilStenstrom** [EmilStenstrom/django-components#518]
We currently have a templates directory that contains some templates used by tests. But having them in a separate directory means we have to look inside several files when trying to find what a certain test does. It also encourages tests to reuse the same file for more than one test, which isn't a good idea when you want tests independent of each other.

So lets go through all the templates in https://github.com/EmilStenstrom/django-components/tree/master/tests/templates and inline them (copying if needed) the templates into their respective test cases.

**Comment by JuroOravec** [comment]
I think we can close this one. Had a look, and almost all files in `tests/templates` are used with either `{% extends %}`, `{% include %}`, or inside the tests we check if the file was imported. So these templates have to stay as separate files.

- block_in_component_parent.html
- block_in_component_provide.html
- block_in_component.html
- block_in_slot_in_component.html
- block.html
- dynamic_svg1.svg
- dynamic_svg2.svg
- inject.html
- mdn_complete_page.html
- simple_template.html
- slot_inside_block.html
- slotted_template.html

Only [mdn_component_template.html](https://github.com/EmilStenstrom/django-components/blob/master/tests/templates/mdn_component_template.html) could be inlined.
