### ISSUE TITLE
Allow to render a component, passing args and kwargs, from Python

### ISSUE THREAD

**Issue by JuroOravec** [EmilStenstrom/django-components#520]
This is what I called the "Inlined component render" in https://github.com/EmilStenstrom/django-components/issues/483.

## Description

The idea is that I want to be able to render a component in Python, but using the same inputs (args and kwargs) like I would if I rendered the component inside a Django template via `{% component %}` tag.

So if component's template interface is:
```django
{% component "my_comp" data height=123 width=456 readonly=True %}
{% endcomponent %}
```

Then I'd like to be able to call the component from inside Python like so:
```py
content = MyComp.render_from_input(data, height=123, width=456, readonly=True)
# or
content = MyComp.render_from_input(args=[data], kwargs{"height": 123, "width": 456, "readonly": True})
```
and get back the rendered content as a string.

## Why?

I mostly do this when I want to nest rendered data into other data structures.

E.g. currently I have a `table` component, which accepts a list of `TableRow`s, whereas `TableRow` is roughly:
```py
@dataclass
class TableRow:
	cols: Dict[str, TableCell]
	attrs: str|None = None
	klass: str|None = None

@dataclass
class TableCell:
	content: str
	attrs: str|None = None
	klass: str|None = None
	href: str|None = None
```

So with this, I can construct tables, but I can tweak styling / HTML attributes on the level of rows AND cells. Or make specific cells to act as links.

But you see above that `TableCell` accepts a `content` as string. I have some elaborate content inside the table cells, e.g. an icon that acts as a button. But the icon is defined as an `icon` component. So I first need to render the `icon` to string, and then pass the result into `TableCell` to achieve that.

```py
row = TableRow(
	cols={
		"save": TableCell(
			content=IconComp.render(...),
			...
		)
	}	
)
```

## Current state

Currently, `Component` class has 3 rendering methods - `render`, `render_from_input`, and `render_to_response`.
- `render_to_response`
	- Part of [`django.views.View` API](https://github.com/django/django/blob/main/django/views/generic/base.py#L190), this method allows the components to behave as Views.
	- Calls `render`.
	- Allows to pass slot fills in Python
	- **Doesn't** handle args and kwargs
- `render_from_input`
	- Used by `ComponentNode`, so used when we render the component inside a Django template as `{% component ... %}`.
	- Calls 'render`
 	- **Doesn't** handle slot fills
	- Accepts args and kwargs.
- `render`
	- The common path for both `render_to_response` and `render_from_input`.
	- 	*Doesn't* accept args and kwargs, and instead expects the args/kwargs to be pre-processed into a Context instance.

NOTE: Initially I thought that `Component.render` needs follow the `Node.render` API, but this is not true. `ComponentNode.render` has to follow `Node.render` API, but `Component.render` can be whatever!

So the problem is that currently, we don't have a unified interface for rendering a component from inside Python
- `render_from_input` accepts args and kwargs but doesn't handle slots
- `render_to_response` handles slots but doesn't accept args and kwargs
- `render` requires users to pre-process the args and kwargs themselves.

## Future state

So instead I suggest to merge these to have singular interface that can handle both args & kwargs, AND slots, AND can accept a Context:

```py
def render(
    self,
    context: Union[Dict[str, Any], Context] = None,
    args: Optional[Union[List, Tuple]] = None,
    kwargs: Optional[Dict[str, Any]] = None,
    slots: Optional[Dict[SlotName, str]] = None,
    escape_slots_content: bool = True,
) -> str:
```

And because we still need `render_to_response`, then `render_to_response` would be just a thin wrapper around `render`, that wraps the content in an HtmlResponse class.

## API

While the new `render` is fairly flexible, then if we wanted to call it in Python, we'd still need to instanciate the class:
```py
MyComp("").render(args=args, kwargs=kwargs, ...)
```

A nicer API would be if we could call `render` as a class method:
```py
MyComp.render(args=args, kwargs=kwargs, ...)
```

I think it's safe to use `render` as class method, because all the data that's passed to Component at instantiation are related component's behavior when it's nested in the template:
```py
component: Component = component_cls(
    registered_name=resolved_component_name,
    outer_context=context,
    fill_content=fill_content,
    component_id=self.component_id,
)
```
- `registered_name` - Not relevant when component rendered directly
- `outer_context` - None when called directly, because component is not nested
- `fill_content` - Handled by the `slots` input to `Component.render`, so no need to set that at instantiation
- `component_id` - No need to set it, as component will define one internally automatically if not set.
---

What do you think?

**Comment by JuroOravec** [comment]
@EmilStenstrom Let me know what you think.

Also @dylanjcastillo you have the best understanding of how `render_to_response` is used, are there any edge cases / caveats to be aware of?

**Comment by JuroOravec** [comment]
I've made an MR for this here https://github.com/EmilStenstrom/django-components/pull/521

**Comment by dylanjcastillo** [comment]
Hey @JuroOravec, I see that you already created the PR. But, in any case, no caveat that I can remember.
