### ISSUE TITLE
This hyperlink is dead - There is no "Registering Components" in latest readme (0.82)

### ISSUE THREAD

**Issue by TimothyMalahy** [EmilStenstrom/django-components#534]
https://github.com/EmilStenstrom/django-components/blob/a4b4905bee778a51f9a99a042ce14ed2424cc9fb/README.md?plain=1#L31

**Comment by JuroOravec** [comment]
Ah right, so I plan to add the "Registering Components" section to the README as part of an MR that refactors and documents the usage of `ComponentRegistry`. And the entry in the table of contents slipped in.

Fixed in https://github.com/EmilStenstrom/django-components/pull/535
