### ISSUE TITLE
safer_staticfiles working?

### ISSUE THREAD

**Issue by j2l** [EmilStenstrom/django-components#536]
Hello,
Discovering your great plugin by following https://www.youtube.com/watch?v=Pnp9IIxOXPU 
With 'django_components.safer_staticfiles', [http://127.0.0.1:8000/static/card/card.py](javascript:void(0);) is still downloadable for me (django 5.0.6, django_components 0.82), you too?

```python
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    # 'django.contrib.staticfiles',
    'django_components',
    'django_components.safer_staticfiles',

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        #'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
            'builtins': [
                'django_components.templatetags.component_tags',
            ],
            'loaders':[(
                'django.template.loaders.cached.Loader', [
                    'django.template.loaders.filesystem.Loader',
                    'django.template.loaders.app_directories.Loader',
                    'django_components.template_loader.Loader',
                ]
            )],

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    #os.path.join(BASE_DIR, "components"),
    BASE_DIR / "components"
]
```
also, test https://dhc.iwanalabs.com/static/click_to_edit.py

**Comment by JuroOravec** [comment]
Hey @j2l, great to hear that you like it! And thanks for including the details and settings. I'll have a look in the next few days

**Comment by JuroOravec** [comment]
Ok, I looked into it, and this is what I found:

1. `safer_staticfiles` modifies the `ignore_patterns` attribute of `django.contrib.staticfiles.apps.StaticFilesConfig`  in https://github.com/EmilStenstrom/django-components/blob/master/src/django_components/safer_staticfiles/apps.py#L16.

2. `safer_staticfiles` excludes the `.py` and `.html` files for `collectstatic` command:
	```sh
	python manage.py collectstatic
	```
	and for prod deployment, e.g.:
	```sh
	gunicorn sampleproject.wsgi:application
	```
	but it does NOTHING on the dev server:
	```sh
	python manage.py runserver
	```

3. Based on this, I believe that the example with [dhc.iwanalabs.com/static/click_to_edit.py](https://dhc.iwanalabs.com/static/click_to_edit.py) is actually either not using `safer_staticfiles`, or is deployed using the `runserver` command. @dylanjcastillo can you confirm this?

4. TODO - We should document `safer_staticfiles` better.

5. I'd be great to have a test to check that `safer_staticfiles` does indeed exclude `.py` and `.html` files.

	I tried to write a test with [`StaticLiveServerTestCase`](https://docs.djangoproject.com/en/5.0/topics/testing/tools/), but it still allows to access ALL files, so it's like running a dev server.

	Another thing I may try to do as a test where we would subclass `Command` of `django.contrib.staticfiles.management.commands.collectstatic` and override the `copy_file`, `delete_file` and `clear_dir`, and then run `Command.collect`, and check if it includes the python and html files or not. 

	But if someone else knows how we can test this better, please chip in!

**Comment by dylanjcastillo** [comment]
@JuroOravec yes, [dhc.iwanalabs.com/](https://dhc.iwanalabs.com/) isn't using `safer_staticfiles` on purpose.

**Comment by JuroOravec** [comment]
@dylanjcastillo Thanks!

With that, @j2l can we close this issue? Have you checked `safer_staticfiles` with `collectstatic` or prod deployment?

Lastly I added notes + tests for `safer_staticfiles` in https://github.com/EmilStenstrom/django-components/pull/538. @EmilStenstrom would you give it a look? Thanks!

**Comment by j2l** [comment]
Thank you @JuroOravec 
I confirm it works with gunicorn, after collectstatic
Precision: 
WITHOUT `'django_components.safer_staticfiles'`.

'django_components.safer_staticfiles' is useful for collectstatic, but must be commented afterwards (or you get a 500). STATICFILES_DIRS is not needed anymore too.

To encourage the best practice to not have .py in any static folder (and teach me how), would you please add a "how to" run components py NOT in any accessible folder? Basically, the same way it works with gunicorn in the end.

I'm happily surprised embedded templates and scripts in components are working well from the server with gunicorn!

**Comment by JuroOravec** [comment]
Hey @j2l, so I tried again:
1. I cleaned the `staticfiles` dir
2. Ran collectstatic
3. Ran the app with gunicorn

And now I couldn't access even JS/CSS files (these should be accessible).

Maybe I'm missing something, but there might be something wrong. So I'll reopen this one.

**Comment by j2l** [comment]
What error do you get?

**Comment by j2l** [comment]
Good to see you made it work! Thank you @JuroOravec
