### ISSUE TITLE
Auto-merge dependabot PRs?

### ISSUE THREAD

**Issue by EmilStenstrom** [EmilStenstrom/django-components#575]
Dependabot creates PRs each time there's a dependency that needs updating. 

We have two types of dependencies:
1) Django, which is the only thing the library depends on
2) 33 development dependencies

Idea: If the tests pass can we automatically merge dependabot updates? Only 2 or (1 and 2)?

Here's the config needed to do it: 
https://stackoverflow.com/questions/64116781/how-do-i-automerge-dependabot-updates-config-version-2

**Comment by EmilStenstrom** [comment]
Another option would be to unpin development updates. That way we would always be on the latest version...

**Comment by JuroOravec** [comment]
I think the option with auto-merging after success tests I the best here
