### ISSUE TITLE
Doc table of contents links not working

### ISSUE THREAD

**Issue by mikko-ahonen** [EmilStenstrom/django-components#576]
On the page:

https://pypi.org/project/django-components/

The table of contents links do not work. Some images also appear to be broken.

**Comment by JuroOravec** [comment]
After https://github.com/EmilStenstrom/django-components/pull/803 is merged and released as v0.115, we should check for any broken links on the PyPI page.

**Comment by JuroOravec** [comment]
No longer applicable as the large chunk of the docs were moved from README to https://emilstenstrom.github.io/django-components/.

I just had a look at PyPI page. There was a broken link to the license file, fixed it in #834 :)
