### ISSUE TITLE
JS and CSS not loading

### ISSUE THREAD

**Issue by mikko-ahonen** [EmilStenstrom/django-components#577]
I added django components to another project and for some reason I just cannot get it to load CSS and JS dependencies.

I even tried the older version, but apparently I get the same result.

If I include the tags 
    {% component_css_dependencies %}
and
    {% component_js_dependencies %}

I just see these on the HTML:
<script name="JS_PLACEHOLDER"></script>

If I omit the tag, I see nothing.

These tags are not mentioned in the installation, btw, should they be used or not?

I tried both inlining the JS and loading from template, does not seem to make a differenece.

The server is properly serving the files, i.e. I can see

http://127.0.0.1:8000/static/status_board/status_board.py
http://127.0.0.1:8000/static/status_board/status_board.html
http://127.0.0.1:8000/static/status_board/status_board.js
http://127.0.0.1:8000/static/status_board/status_board.css

**Comment by EmilStenstrom** [comment]
Hi! Here's the docs for those three tags: https://github.com/EmilStenstrom/django-components?tab=readme-ov-file#rendering-jscss-dependencies

I'm wondering: Have you set RENDER_DEPENDENCIES without enabling the middleware?

**Comment by EmilStenstrom** [comment]
ping @mikko-ahonen

**Comment by JuroOravec** [comment]
@mikko-ahonen Is this still relevant? As of v0.117, this should now work correctly.

**Comment by tanssinet** [comment]
I solved it somehow, but I don't remember how anymore. I think we can close this.
