### ISSUE TITLE
Allow different apps to have different settings

### ISSUE THREAD

**Issue by JuroOravec** [EmilStenstrom/django-components#590]
For the UI component library, I came across an issue that inside the library I want to use certain settings:

```py
COMPONENTS = {
    "context_behavior": "isolated",
    "tag_formatter": "django_components.component_shorthand_formatter"	
}
```

But I want to allow users to use different settings.

Since the components within the library render each other, it would break if the end user changed the `tag_formatter` setting.

E.g. if, within the UI library I referenced a component in another using the "ShorthandComponentFormatter":

```django
{% button %}
{% endbutton %}
```

But user's settings would require to use different format:

```django
{% component "button" %}
{% endcomponent %}
```

---

Currently, there's 5 settings: `autodiscover`, `libraries`, `template_cache_size`, `context_behavior`, `tag_formatter`
- Of these, `autodiscover` and `libraries` kinda are "global" settings. They are not used in the code, just to import things at the startup
- `template_cache_size`, `context_behavior`, `tag_formatter`, however, are used in template tags, `ComponentRegistry`, `Component`.
- I'm thinking that, the 3 settings above are directly or indirectly associated with `ComponentRegistry` instance that holds the components. So maybe we could add a `settings` field which would hold the 3 settings. And the settings set in `settings.py` would just pass the values to the default subclassed `Library`.
- Getting the settings info to slots will have to be through the Context, similarly as we do it [here](https://github.com/EmilStenstrom/django-components/blob/03af25aad6841b6edb56c925d2599817e08ceb44/src/django_components/component.py#L432).

So to allow different settings, one would create their own instance of `ComponentRegistry` (optionally also their own `Library`)

```py
my_lib = django.template.Library()
my_reg = ComponentRegistry(
    library=my_lib,
	settings={
		"context_behavior": "isolated",
		"tag_formatter": "django_components.component_shorthand_formatter",
		"template_cache_size": 256,
	},
)
```

And then, to use the correct registry, one would register components like so:

```py
@component.register("adivider", my_reg)
class ADivider(component.Component):
	...
```

What this should do is that if user installs a 3rd party django app, then user should be able to configure their components independently from the 3rd party app:

```django
{% load third_party_app %}

{% component "mycomp" %}             <--- Uses default tag formatter
	{% adivider / %}                 <--- Uses "shorthand" tag formatter
{% endcomponent %}
```

**Comment by EmilStenstrom** [comment]
@JuroOravec I like this. It allows mixing your own "django-like" components with external isolated components from some library author. Good solution!
