### ISSUE TITLE
Allow dynamic components

### ISSUE THREAD

**Issue by JuroOravec** [EmilStenstrom/django-components#612]
Similarly to https://github.com/EmilStenstrom/django-components/issues/587,  I was thinking of making it possible to pass variables as component names, to allow for dynamic components.

But it turns out that we would need to take a different approach.

This is because the TagFormatter feature, which works at template compile time. And the TagFormatter MUST work at compilation time, because it generates the "end tag" (e.g. `endcomponent` or `endbutton`), which is then used to inform Django how much of the remaining content to parse.

In theory we could have "start tag" generated at render-time, and "end tag" at compile-time, but that feels weird.

So instead I'm thinking of a standalone template tag. Similar to [django-cottons `<c-component :is="..." >`](https://github.com/wrabit/django-cotton#dynamic-components), or [Vue's `<component :is="..." />`](https://vuejs.org/guide/essentials/component-basics.html#dynamic-components) (tbh, django-cotton is inspired by Vue too). 

Since the `{% component %}` template tag is already taken by our regular components, it would have to be something else. `dynamic_component` is too long, but `xcomponent` could work.

How it works is that one would use this tag the same way as they would use a concrete component. So they would pass on all the args and kwargs they want, and optionally `only` flag or `/` for an inline block.

But they would pass also one more parameter, which specifies the component that should be invoked. At first I used `name`, but tbh I like `is` more, as Vue does it, simply because it's less likely that people will use a parameter called `is`.

So imagine a scenario where an icon can be rendered in multiple different ways, depending on the component input. And based on the input, `icon_component` is assigned a name of one of the components.

```django
{% xcomponent is=icon_component size="24" color="black" %}
{% endxcomponent %}
```

IMO `is` parameter should accept both string (registered component name) and Component class (pass directly by reference).

**Comment by EmilStenstrom** [comment]
I'm not fond of leaving the simplicity of "django-component just adds one new template tag, component!" (yeye, slot/fill, but that doesn't count if we're doing marketing :)).

I think you could implement this inside a normal component if you wanted? So `{% component "dynamic" is=icon_component %}` would call the dynamic component (that the user would write themselves) and delegate to icon_component.

**Comment by JuroOravec** [comment]
Hm, so the issue with the tag formatters. 

Your example works only for the default formatting. But what if someone used the "shorthand" one?

```django
{% button %}
{% endbutton %}
```

One way this could work is that, for the "shorthand" formatting, it would work like this:

```django
{% dynamic is=icon_component %}
{% enddynamic %}
```

So basically, we would give a component "dynamic" a special meaning. While this can work too, I'm not a fan of special rules and exceptions. That's why I'm leaning more for a separate tag.

**Comment by JuroOravec** [comment]
Hm, actually what could also work is if we provided the function that takes the two arguments, e.g. `resolve_component(comp_name, registry?)`, and then documented in README how people can write a component that dynamically loads a component.

But if we do that, IMO we'd be better off to go all the way and implement it. This is similar to [this point you made on offering one obvious way to do it](https://github.com/EmilStenstrom/django-components/issues/613#issuecomment-2308985320). If we provide only the building blocks, but we won't cover common use cases, then people will come up with 20 ways address that issue.

**Comment by EmilStenstrom** [comment]
@JuroOravec I see your point. And looking at the concrete examples from django-cotton (the form fields) I do finally think I see why this would be useful (examples like that makes things concrete!).

So going back to how this could work, I think we should implement this as a component (inheriting from Component and all...), not write a custom template tag. This component will take two arguments, and delegate all the work to the components it references. We could let people register this component with their own name, sidestepping the problem with picking a good general name altogether. 

What do you think?

**Comment by JuroOravec** [comment]
Sounds great!
