### ISSUE TITLE
Broken link in documentation

### ISSUE THREAD

**Issue by WhyNotHugo** [EmilStenstrom/django-components#646]
In [the main page](https://emilstenstrom.github.io/django-components/latest/), there is a link labelled "[See the example project](https://emilstenstrom.github.io/django-components/latest/sampleproject)" which leads to a 404 page.

**Comment by WhyNotHugo** [comment]
I think that it's not deployed yet.

I know where to look anyway, since [the commit fixing the link](https://github.com/EmilStenstrom/django-components/pull/648/commits/91e5a2940d598fce0486cfe0507195ee66c2f306) has the correct link :)

**Comment by EmilStenstrom** [comment]
It seems to work fine for me, from the README.md
