### ISSUE TITLE
Docs not deployed to gh-CDN

### ISSUE THREAD

**Issue by dalito** [EmilStenstrom/django-components#650]
The documentation build process and pushing of the updated docs to gh-pages branch has been working fine for the recent PR merges.

However, the deployment to gh-CDN is not happening. The job is not starting, see https://github.com/EmilStenstrom/django-components/actions/workflows/pages/pages-build-deployment The last time it ran was two weeks ago.

I speculate that it is some config setting in the repo. In my fork the whole deployment process was always working with exactly the same `docs.yaml` workflow file.

**Comment by JuroOravec** [comment]
Btw, where and how is the `pages-build-deployment` workflow triggered? Wasn't aware of it

**Comment by EmilStenstrom** [comment]
![image](https://github.com/user-attachments/assets/568023ff-f87c-4ef7-af14-0a0e56e31e05)

Here's the full config.

**Comment by dalito** [comment]
Ah, you have to change the source to "deploy from branch" and select the gh-pages branch.

![image](https://github.com/user-attachments/assets/2681df76-b420-4b76-b131-2ef6ef06d366)

**Comment by EmilStenstrom** [comment]
Updated! 
![image](https://github.com/user-attachments/assets/298a8f9e-735b-4f3e-bbba-0ea861f988cd)

**Comment by dalito** [comment]
...and the docs got deployed. Great!
