### ISSUE TITLE
Automate releases to PyPI with GitHub Actions

### ISSUE THREAD

**Issue by EmilStenstrom** [EmilStenstrom/django-components#69]
In an attempt to make this project less dependent on me I'd like to automate releases to PyPI. I think a good way to do this is to move the PyPI account from my personal to a new one, put the secrets for the new one as GitHub environment variables, and make a GitHub Action that uses them to push new releases to PyPI. That way, everyone with GitHub access to django-components will also be able to make releases.

**Comment by hanifbirgani** [comment]
To use the action file, you need to set the the PyPI access token as an environment secret with `PYPI_API_TOKEN` key in Github settings. The action publishes new releases for every tagged branch of github repo.

**Comment by EmilStenstrom** [comment]
Wow, this is great! Just what I was looking for!

Do you know if there are any security considerations I should be aware of when enabling this?

**Comment by hanifbirgani** [comment]
As long as you store your token as an environment secret, it's ok.
The action automatically publishes tagged commits to PyPI, so you should be careful when creating new tags, cause the tags will create new releases on PyPI.

**Comment by EmilStenstrom** [comment]
Thanks! I also see that it only depends on official github and pypa plugins too. Really appreciate this!
