### ISSUE TITLE
Component View and LoginRequiredMixin

### ISSUE THREAD

**Issue by RimJur** [EmilStenstrom/django-components#690]
# Details

I've decided to use newly added (Django 5.1) LoginRequiredMixin to the django project. Then I've decorated function based view with `@login_not_required` decorator and class based views with `@method_decorator(login_not_required, name="dispatch")` decorator.

Of course, I've tried to do the same to the component view. It didn't work.

# What I've tried

1. Decorating the whole Component class with `@method_decorator(login_not_required, name="dispatch")`
2. Adding `@method_decorator(login_not_required)` to the `get` or `post` component methods.
3. Overriding the view inside the component, as documentation suggests:
```
class Component(Component):
    ....
    ....
    @method_decorator(login_not_required, name="dispatch")                                                                                                                                 
           class View(ComponentView):                                                                                                                                                             
               def setup(self, request, *args, **kwargs):                                                                                                                                         
                    super(request, *args, **kwargs) 
```

None of these were successful. The View is redirecting to login page. This is the expected result of LoginRequiredMixin for unauthorized view.

P.S. Really enjoy working with this package. Documentation is great, this is the first time running into an issue.

**Comment by EmilStenstrom** [comment]
Hi,

Thank you for reaching out and for your kind words about the package! I'm glad to hear you're enjoying working with it.

With some heavy help from ChatGPT o1:
> 
> Regarding your issue with applying the `login_not_required` decorator to a component's view: the reason your attempts didn't work is likely due to how `ComponentView` is structured in the `django-components` package.
> 
> In Django 5.1, to exempt a class-based view from the login requirement enforced by `LoginRequiredMiddleware`, you can set the `login_not_required` attribute directly on the view class. This approach is more straightforward and ensures that middleware recognizes the exemption.
> 
> Here's how you can modify your component:
> 
> ```python
> from django_components import component
> 
> @component.register("your_component")
> class YourComponent(component.Component):
>     # Your component's code...
> 
>     class View(component.ComponentView):
>         login_not_required = True  # Exempt this view from login requirement
> 
>         def setup(self, request, *args, **kwargs):
>             super().setup(request, *args, **kwargs)
>             # Your setup code...
> 
>         # Define your GET or POST methods if needed
>         def get(self, request, *args, **kwargs):
>             # Your GET method code...
>             pass
> ```
> 
> By setting `login_not_required = True` on the `View` class, you inform Django's middleware that this view should not enforce the login requirement. This should prevent the redirect to the login page and allow unauthorized users to access the component's view.
> 
> **Why your previous attempts didn't work:**
> 
> - **Using `@method_decorator`**: Applying `@method_decorator(login_not_required, name="dispatch")` doesn't work as expected because the decorator might not properly interact with the `ComponentView`'s dispatch mechanism.
>   
> - **Overriding methods with decorators**: Similarly, decorating individual methods like `get` or `post` doesn't ensure that middleware recognizes the exemption, since middleware checks the `login_not_required` attribute on the view class itself.
> 
> **Additional Tips:**
> 
> - Ensure that any middleware enforcing login requirements (like `LoginRequiredMiddleware`) is appropriately configured and respects the `login_not_required` attribute.
>   
> - If you have multiple components that need to be exempt from login requirements, you can create a base view class with `login_not_required = True` and inherit from it.
> 

Would you mind giving that a try? Please let me know if you have any further questions or if this solution doesn't work as expected.

**Comment by RimJur** [comment]
Thanks for such a fast answer!

Tinkering with o1-preview and the source code I managed to steer the llm to come up to a solution.

```python
class View(ComponentView):
        @classmethod
        def as_view(cls, *args, **kwargs):
            view = super().as_view(*args, **kwargs)
            view = login_not_required(view)
            return view

        def setup(self, request, *args, **kwargs):
            super().setup(request, *args, **kwargs)
```

For anyone also facing this issue, just use this View inside your Component class.

**Comment by EmilStenstrom** [comment]
Happy to hear you solved it!
