### ISSUE TITLE
Passing Undefined Context Variables to a Component Template in Django?

### ISSUE THREAD

**Issue by Yaso2Go** [EmilStenstrom/django-components#691]
I’m trying to create a reusable component in Django with an image tag that uses context variables defined in the parent template. 

Currently, in my `component.html`, I have:
`<img src="{% static 'img/' %}{{ fields.form_name" alt="{{fields.title}}" class="content_image img-fluid">`. 

However, `fields.form_name` and `fields.title` are not defined in `component.html`, leading to issues when rendering.

I want to call this component using:
`{% component "image" %}`

and have it automatically use the context variables from the parent template.

**Comment by EmilStenstrom** [comment]
I think the easiest way to solve this would be to pass the fields to the image component? So `{% component "image" fields %}`?

If you do want to access the outer context from your component, there's a section for this in the docs: https://github.com/EmilStenstrom/django-components?tab=readme-ov-file#component-context-and-scope

**Comment by Yaso2Go** [comment]
> I think the easiest way to solve this would be to pass the fields to the image component? So `{% component "image" fields %}`?
> 
> If you do want to access the outer context from your component, there's a section for this in the docs: https://github.com/EmilStenstrom/django-components?tab=readme-ov-file#component-context-and-scope

First of all thank you for the kind response, second is that i actually dont quite understand it. What i have gave you is a snippit from the code but in reality its much bigger where i add custom template tags and built in django function, the full code im tryting to import is this:

`<img src="{% static 'img/' %}{{ fields.form_name|default_if_none:'default_pfp.png' }}.{{ fields.form_name|get_image_format }}" alt="{{fields.title}}" class="content_image img-fluid">`

I cant quite figure how to make the component get context from its parent file

Here is the image/component.py file

```
@register("image")
class image(Component):
    def get_context_data(self, fields, format):
        
        return {
            "fields": fields,
            "format": format
        }
        
    template= """
        <div id="progressContainer" class="progress-container" style="margin-top: 2vh;">
            <div class="progress">
                <div id="progressBar" class="progress-bar progress-bar-striped progress-bar-animated" role="progressbar" style="width: 0%;" aria-valuenow="0"
                    aria-valuemin="0" aria-valuemax="100"></div>
            </div>
        </div>

        <!-- Display the uploaded image or default image -->
        <img src="{% static "img/" %}{{ fields.form_name|default_if_none:'default_pfp.png' }}.{{ format }}"
            alt="{{fields.title}}" class="content_image img-fluid">
    """
```

What i understood is that i need to do something with the get_context_data function but cant quite get it, thanks in advance for your help!!!

**Comment by JuroOravec** [comment]
@Yaso2Go Do I understand right that you want to call the `image` component from within another template as `{% component "image" %}`?

E.g.

```django
<div>
  {% component "image" / %}
<div>
```

Assuming that the rendering context has variables `fields` and `format`?

If so, as @EmilStenstrom mentioned, you can use `self.outer_context` to access the outer context from within `get_context_data`. Here's an example:

```py
class MyComponent(Component):
    template = """
        Variable: <strong>{{ fields.title }}</strong>
    """

    def get_context_data(self):
        outer_fields = self.outer_context["fields"]
        return {
            "fields": outer_fields,
        }
```

---

However, as a best practice, I suggest you do not do that, and instead explicitly pass the variables as you do already [in your example](https://github.com/EmilStenstrom/django-components/issues/691#issuecomment-2395601364). In 6 months, or if someone else joins your codebase, you / they will have no idea where the `field` and `format` variables are coming from.

---

IMO, as part of this ticket, we should add an example to that section in README, so the usage is clear :)

**Comment by Yaso2Go** [comment]
@JuroOravec I have done a pull request to add this to the README, thank you

**Comment by Yaso2Go** [comment]
Now that i have tested it i found a few issues, first using other context i cant import custom template tags that i have made, as well as that i cant import django template tags such as `{% static "css/" %}`

**Comment by JuroOravec** [comment]
@Yaso2Go Could you show an example of the code where you get the errors?

**Comment by Yaso2Go** [comment]
Sure thing, here is my code
from django_components import Component, register

```
@register("image_display")
class image_display(Component):        
    template= """
        <!-- Display the uploaded image or default image -->
        <img src="{% static "img/" %}{{ fields.form_name|default_if_none:'default_pfp.png' }}.{{ fields.form_name|get_image_format }}"
            alt="{{fields.title}}" class="content_image img-fluid">
    """
    
    def get_context_data(self):
        outer_fields = self.outer_context["fields"]

        return {
            "fields": outer_fields,
        }
```

The first error i get is
`TemplateSyntaxError("Invalid block tag on line 3: 'static'. Did you forget to register or load this tag?")`

And then i tried removing the `{% static "img/" %}` from my `img` elemnt in the template code and when i ddi so i got another error saying: `TemplateSyntaxError("Invalid filter: 'get_image_format'")`

Keep in mind that the `get_image_format` filter is a custom template tag that i have made that is located in `app_name/templatetags/custom_tags.py`.

When i remove the field that contains this filter too the page loads but dont work cause its lacking those necessary functions to make it work. Thank you for your help

**Comment by JuroOravec** [comment]
@Yaso2Go Looks like the issue is that the `static` nor your custom template tags are not loaded in the template.

What does your settings look like? Have you configured the template tag "builtins"? ([See docs here](https://docs.djangoproject.com/en/5.1/topics/templates/#module-django.template.backends.django), and scroll a bit down to "builtins")

- If you have not configured "builtins", then this is an expected behavior, and you are simply missing the `{% load %}` tags:

	```django
	{% load static custom_tags %}
	
	<!-- Display the uploaded image or default image -->
	<img src="{% static "img/" %}{{ fields.form_name|default_if_none:'default_pfp.png' }}.{{ fields.form_name|get_image_format }}"
	    alt="{{fields.title}}" class="content_image img-fluid">
	```

- If you HAVE configure "builtins" in the settings, and you expected "static" and your custom template tags to be auto-loaded, then that would be an issue with django_components

**Comment by Yaso2Go** [comment]
@JuroOravec Yesssss, loading static and custom_tags in the component itself solved the issue, thank you soo much for your help!!! I can now continue developing with ease of mind 😁

**Comment by JuroOravec** [comment]
Awesome, glad I could help :)

---

Btw, this depends on personal taste, but for me the component could be made easier to read by moving the logic of constructing the image URL into `get_context_data`, e.g. something like this:

```py
from django.templatetags.static import static

from myapp.templatetags.custom_tags import get_image_format

@register("image_display")
class image_display(Component):        
    template= """
        <!-- Display the uploaded image or default image -->
        <img src="{{ src }}" alt="{{ fields.title }}" class="content_image img-fluid">
    """
    
    def get_context_data(self):
        outer_fields = self.outer_context["fields"]

        img_dir = static("img/")
        filename = fields.form_name or 'default_pfp.png'
        suffix = get_image_format(fields.form_name)
        src = f"{img_dir}{filename}.{suffix}"

        return {
            "fields": outer_fields,
            "src": src,
        }
```
