### ISSUE TITLE
templatetags folder is missing when installed by pip 

### ISSUE THREAD

**Issue by PhakkyoC** [EmilStenstrom/django-components#7]
Hi,

I tried to use this package but i noticed that the folder templatetags is missing because i don't have component_tags.

I use python 3.8.3 and pip 20.1.1 with django 3.0.7

I have to manualy download the missing file to use components.

**Comment by EmilStenstrom** [comment]
@PhakkyoC Could you show the error-message you get? Did you install via pip?

**Comment by PhakkyoC** [comment]
@EmilStenstrom Yes i use pip to instlall it with "pip install django_reusable_components" but i don't have any error while installing.
I noticed the file component_tags.py is missing. So i tried to uninstall/install many times but it's still missing.

The errors i encoutered was because i don't have the file component_tags.py while starting my server or trying to load my templates

**Comment by EmilStenstrom** [comment]
Thanks for reporting, I'll look into it. 

setup.py is set to include the whole django_components directory when installing, including all subdirectories, so this is strange.

Would you mind posting your exact error, so I can quickly reproduce it?

**Comment by PhakkyoC** [comment]
I'll try to show you what i did to get errors

![install](https://user-images.githubusercontent.com/38459574/86327350-716cae00-bc43-11ea-999d-e826cd318c65.png)

So i don't have any errors when installing but when i try to add builtins like the exemple :

![buildin](https://user-images.githubusercontent.com/38459574/86327466-b09aff00-bc43-11ea-931a-7598d2830f9a.png)

and when i use manage.py runserver

![buildinErr](https://user-images.githubusercontent.com/38459574/86327506-bd1f5780-bc43-11ea-9527-f633c2e8c736.png)

So, i tried to remove builtins and use "{% load django_components %}" in my templates, the server run but i still can't use components 

![template err](https://user-images.githubusercontent.com/38459574/86327756-0ff90f00-bc44-11ea-8a7e-e8bce5983112.png)

**Comment by EmilStenstrom** [comment]
This was indeed a packaging issue. Seems just specifying "django_components" does not include subdirectories, which means I ended up with a package without the templatetags directory, just like you said.

I've now fixed this (using setuptools.find_packages instead of specifying the package name) and released version 0.3 to pypi. Would you mind checking it out and let me know if you find any issues? (I've tried it myself, triggered the issue with <0.3 and not with 0.3).

Thanks for reporting!
