### ISSUE TITLE
Desactivating cache during component dev

### ISSUE THREAD

**Issue by tchappui** [EmilStenstrom/django-components#718]
Hello and thank you for your wonderful work with django components.

I have a caching issue when developping components using django-component. Refreshing my browser after component updates is not enough and, even wth reload_on_template_change=True, I continuoudly need to manually restart the dev server for the changed to be updated in the browser.

I guess there's a more DX-friendly way of deactivating cache by I cannot figure out how.

Best wishes

Thierry

**Comment by cristianrat** [comment]
having the same issue @tchappui 
What's your solution?

**Comment by maximbelyayev** [comment]
+1
