### ISSUE TITLE
component_shorthand_formatter and dynamic components

### ISSUE THREAD

**Issue by vb8448** [EmilStenstrom/django-components#764]
Are dynamic components supported with the component_shorthand_formatter?
In the docs the only example is with the classical `component` tag.

I've also looked in issues and discussions but didn't find anything.

As a workaround, I'm rendering the component inside the django function like `output = MyComponent.render(kwargs={...})` and then i pass `output` as context and just render it as `{{ output }}`.

Thanks.

**Comment by JuroOravec** [comment]
Yes, the dynamic component is implemented as a regular Component class, so the shorthand format should work:

```django
{% dynamic is=MyTable data=data %}
{% enddynamic %}
```

---

I'm leaving this issue open, as we could add tests and update docs with this case.

**Comment by vb8448** [comment]
@JuroOravec it works. Thanks.
