### ISSUE TITLE
Enable Projects for this repo

### ISSUE THREAD

**Issue by JuroOravec** [EmilStenstrom/django-components#795]
Hi @EmilStenstrom, could we enable Projects for this repo? I used to track features that I wanted to implement for django-components in my fork (https://github.com/users/JuroOravec/projects/1/views/1), but now it feels like the things to do are exploding  (I get this feeling when I try to keep ~ 12 and more things in my head). So it'd help to write them out as issues, and put them all in a kanban. As a nice bonus people would get to see the planned features / roadmap.

**Comment by JuroOravec** [comment]
These are the things bouncing in my head:

Bugs:
1. Fix the order of JS in `Component.Media.js`
2. Fix https://github.com/EmilStenstrom/django-components/issues/793

Prep for plugins:

3. Refactor template tag parsing (see `component_tags`)
4. Have only 1 template per component
   - This consists of:
       5. Remove `get_template()` and `get_template_name()`
       6. Add `on_render()` as replacement for the above.
       7. `template` can no longer be an instance of `Template`, only string
       8. Add support for `js_name` and `css_name` while we're at it
9. Add plugins system

Docs:

10. Merge the remaining bits
11. Go over the documentatio articles and fix links
12. Add page that lists plugins
13. Add page that lists components

Icons component:

14. (BUG) Make `template_name` and `Media.js/css` to resolve lazily.
15. Tests for icon component
16. Release Icon component.

**Comment by EmilStenstrom** [comment]
@JuroOravec Enabled! Great tools to organize ideas and see what's left to do.

I'd love to keep having the high-level discussions about features we have been having in issues, especially as to why you are taking on some parts. For instance, a lot of this is for plugins, and I'd like to hear more about them in an issue.

**Comment by JuroOravec** [comment]
@EmilStenstrom Thanks! And will do, I can create a issues to tie those plugin stuff

**Comment by JuroOravec** [comment]
Btw, @EmilStenstrom looks like you will also have to create a project (called e.g. "Roadmap"). I can only link already-existing projects, and even those have would be have to created by you. So I can't for example link to the project from my fork.

**Comment by EmilStenstrom** [comment]
@JuroOravec There's now a public Roadmap project, that you have full admin access to. GO! :D
