### ISSUE TITLE
jquery problem

### ISSUE THREAD

**Issue by oaltun** [EmilStenstrom/django-components#81]
Hi, 

I am opening a new issue as this seems to be different:

I am still trying to make the calendar example work. templates are found, css works, and js file is loaded. But I get following error in the console:

`script.js:2 Uncaught ReferenceError: $ is not defined`

Search engine results suggest that this happens when jquery is not loaded yet but called.

My guess is the reason is I am using the defer attribute when referencing jquery (cookiecutterdjango does this for all included js files):

 `<script defer src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>`

but the 

` {% component_js_dependencies %}`

tag does not add a defer attribute to the script tag it creates. I moved the jquery reference to the bottom of the page, and deleted the defer attribute. Than everything worked.

**Comment by EmilStenstrom** [comment]
Good catch! The HTML to render the script tag can be overriden by specifying a `render_js_dependencies()` on the Component subclass. You can see the default implementation here: https://github.com/EmilStenstrom/django-components/blob/70fcc162614ee7e7779642ad11dbc12e0d007158/django_components/component.py#L66

Maybe calling super() and `.replace("<script", "<script defer")` could work for you?
