### ISSUE TITLE
{% block %} does not work inside a slot

### ISSUE THREAD

**Issue by philipstarkey** [EmilStenstrom/django-components#97]
I'm really enjoying using this library but I'm running into an issue when I come to factor out common component hierarchies and I'm not sure if I'm doing something wrong, if it's not supported, or a bug.

I'm commonly placing the following (simplified a bit for this example) hierarchy of components in several of my templates:

```
{% component_block "container" %}
  {% slot "content" %}
    {% component_block "card-container" %}
      {% slot "panels" %}
        {% component_block "card" %}
          {% slot "sections" %}
            {% component_block "card-section" %}
              {% slot "content" %}
                {% component_block "heading" %}{% endcomponent_block %}
              {% endslot %}
            {% endcomponent_block %}
          {% endslot %}
        {% endcomponent_block %}
        <form action="{{ action }}" method="POST">
          {% component_block "card" %}
            {% slot "sections" %}
              <!-- content here -->
            {% endslot %}
          {% endcomponent_block %}
          {% csrf_token %}
        </form>
      {% endslot %}
    {% endcomponent_block %}
  {% endslot %}
{% endcomponent_block %}
```

Normally (without using django-components) I'd factor out the HTML (that corresponds to the above) into a base template and use `{% extends %}` and `{% block %}` to place page specific content in place of `<!-- content here -->`. However it appears that the inbuilt `block` template tag only works if it's not nested inside another template tag (e.g. not inside a component slot).

I also tried creating a component whose template contained the above hierarchy of components and placed a `{% slot "innercontent" %}temp{% endslot %}` in place of `<!-- content here -->` but `temp` never got replace by the externally provided slot content. I'm guessing it can't differentiate between the slots in the template providing data to other components and the slots it should be exposing when the component is being used (especially when they are nested within each other).

Is there something I'm missing, or another way to do what I want so I don't have to duplicate the block of nested components over and over again in each template? If not, is it something that can be added easily?

**Comment by EmilStenstrom** [comment]
@rbeard0330 I think you might know the best way forward here. Is it possible to support mixing blocks with slots like Philip assumed above?

**Comment by rbeard0330** [comment]
@philipstarkey, just to make sure I understand your first approach, do you have the whole component tree in the root parent template, with a `{% block sections %}` tag where the `<!-- content here -->` placeholder is?  I don't think there's a good reason that shouldn't work.  That said, Django's template inheritance system is very complicated, so I won't be very surprised if we're screwing up the context in some way that interferes with it.

You're right that the second approach doesn't work right now.  It used to, but it creates a risk of infinite recursions if there are naming collisions, so components currently only get slots from their immediate parent.  An easy fix would be to add an option to allow unsafe global slot searching, but that's not optimal.  I'll think about whether there's a way to do that safely.

It's a bit unwieldy, but you ought to be able to insert an `{% include content_template %}` tag where you want the content, then pass the parent component the path to another template with the content as a prop.

**Comment by philipstarkey** [comment]
@EmilStenstrom @rbeard0330 Thanks for both of your replies. I'll see if I can put together a minimal Django project that demonstrates the issue shortly.

My actual template structure is a little more complicated than your examples, in that I have a template (top) extending a template (middle), which in turn extends another template (base). The base template contains a `{% block content %}` which is overridden by the middle template. It is in this middle template that I'd like to put the components, inside the `content` block, and in turn have a `{% block component_content %}` block defined within a slot of a component which is overridden in the top template. This nesting of blocks works without components.

That said, I also just tried the simpler version of having components in the base template, with a block inside, and overriding the block from within a template that extends the base, and it also didn't work. I'll try and put both examples in the test repo.

I'm not hugely familiar with the internals of the Django templating library, so still trying to wrap my head around how it all works, but is it actually the `{% extends "base.html" %}` template tag that handles the processing of `{% block %}` template tags? It didn't appear like the code for the `{% block %}` tag in Django did much.

**Comment by philipstarkey** [comment]
Ok, I've put together (a probably over the top) example project derived from cookiecutter-django.

Relevant files (since it has a giant amount of boilerplate) are:

Component:
- https://github.com/philipstarkey/django_components_issue97/blob/master/django_components_issue97/users/components.py
- https://github.com/philipstarkey/django_components_issue97/blob/master/django_components_issue97/templates/container.html

Base templates:
- https://github.com/philipstarkey/django_components_issue97/blob/50c99ddb08085e5f43d53638c21da5bc3be05056/django_components_issue97/templates/base.html#L94-L104
- https://github.com/philipstarkey/django_components_issue97/blob/master/django_components_issue97/templates/middle.html

Templates:
- https://github.com/philipstarkey/django_components_issue97/blob/master/django_components_issue97/templates/pages/block_in_component.html
- https://github.com/philipstarkey/django_components_issue97/blob/master/django_components_issue97/templates/pages/block_in_component_in_block.html

The two templates match the two scenarios mentioned in my previous post (simple template inheritance and a more complex template inheritance). Both show the default content of the block inside the component and not the content of the block as defined in the templates.

Let me know if I can do anything more to help!

**Comment by philipstarkey** [comment]
> You're right that the second approach doesn't work right now. It used to, but it creates a risk of infinite recursions if there are naming collisions, so components currently only get slots from their immediate parent. An easy fix would be to add an option to allow unsafe global slot searching, but that's not optimal. I'll think about whether there's a way to do that safely.

And while I'm thinking about this issue, could this be resolved by either an additional argument to `{% slot ... %}` that states the nested slot belongs to the component the template is for, or assuming that a `{% slot %}` inside a `{% slot %}` means the inner slot belongs to the component the template is for, or using a different template tag name to differentiate between "here is the content for the slot" and "here is where the slot content should go" (e.g. `{% component_block ... %}{% slot ... %}{% export_slot ... %}`)? There are probably obvious reasons why these wouldn't work though that I'm unaware of!

**Comment by rbeard0330** [comment]
> And while I'm thinking about this issue, could this be resolved by either an additional argument to `{% slot ... %}` that states the nested slot belongs to the component the template is for, or assuming that a `{% slot %}` inside a `{% slot %}` means the inner slot belongs to the component the template is for, or using a different template tag name to differentiate between "here is the content for the slot" and "here is where the slot content should go" (e.g. `{% component_block ... %}{% slot ... %}{% export_slot ... %}`)? There are probably obvious reasons why these wouldn't work though that I'm unaware of!

@philipstarkey I've been working on something along these lines, which I think will be the best solution.  I've added an optional `exported_as` argument to the slot tag, which causes the parent component to look for a slot under the exported-as name and pass it to the relevant child component under its regular name.  I think this should solve your use case--in your original example, you could export the `sections` slot as `innercontent`.  I'm also working on letting you decide whether to specify new default content for the exported slot or defer to the inner component's default content. 

I'm working out the kinks now, but hopefully should have it available pretty soon.

**Comment by rbeard0330** [comment]
I would actually put it a bit more strongly--that code unambiguously renders the `card` component with an empty `contents` slot.

**Comment by EmilStenstrom** [comment]
In my mind, this gets easier to talk to if we imagine creating slots and filling slots as two different actions.

So your example becomes `{% fill contents %}{% slot body %}{% endslot %}{% endfill %}`, and the version with default contents `{% fill contents %}{% slot body %}Default content for header_card{% endslot %}{% endfill %}`. Am I understanding this correctly?

Which leaves us with these options:

1. {% slot content export_as="body" %}
1. {% fill contents %}{% slot body %}
1. {% slot contents %}{% slot body %} -- The direct decendant of component_block is always a fill, all other calls create new slots.

Thoughts?

**Comment by EmilStenstrom** [comment]
Sorry for the late reply! Thanks for trying to explain to me what the code does. I am a bit lost, and don't have the time to sit down and really understand things properly. So feel free to run with it, I trust that you find the best solution.

I wonder, would it make things easier if we require Components with slots to define the names of those slots in the class?

**Comment by EmilStenstrom** [comment]
@rbeard0330 Did you happen to have some time to think more of this? I think nesting components with slots would be a very useful addition to this library.

**Comment by EmilStenstrom** [comment]
I have split this issue into two different issues, #133 and #134, let's continue the discussion there.
