### ISSUE TITLE
Check if slot is not empty

### ISSUE THREAD

**Issue by alexanderjulmer** [EmilStenstrom/django-components#98]
Some components might have optional slots, e.g.:

```
<div class="frontmatter-component">
    <div class="title">
        {% slot "title" %}Title{% endslot %}
    </div>
    <div class="subtitle">
        {% slot "subtitle" %}Optional subtitle{% endslot %}
    </div>
</div>
```

If implemented as above, the the subtitle div would always be rendered. It could be useful to check whether a slot, here `subtitle` is non empty and then modify the template like so:

```
<div class="frontmatter-component">
    <div class="title">
        {% slot "title" %}Title{% endslot %}
    </div>
    {% if slots.subtitle %}
    <div class="subtitle">
        {% slot "subtitle" %}Optional subtitle{% endslot %}
    </div>
    {% endif %}
</div>
```

When rendering, `_DJANGO_COMPONENTS_ACTIVE_SLOTS` is available but it cannot be used inside the template (see https://docs.djangoproject.com/en/dev/ref/templates/api/#variables-and-lookups).

**Comment by EmilStenstrom** [comment]
@alexanderjulmer That is a great idea. Something that is surely[ missing in block tags too](https://stackoverflow.com/questions/2035385/test-for-existence-of-template-block-in-a-template).

Would you be open to writing up a PR for adding support like you suggest?

**Comment by EmilStenstrom** [comment]
Also ping @hanifbirgani for thoughts. Is changing the syntax worth it for more readable nested slots?

**Comment by lemontheme** [comment]
Happy to say this can now be achieved with the new `{% if_filled <slot_name> %}` tag introduced in v.026. Check out the README to see how it works.

Note to others reading this comment: this is definitely an advanced feature. In many cases you can get similar behavior by nesting an 'inner' slot inside a 'wrapper' slot and filling whichever slot you prefer to keep.
